import React,{useState} from 'react';
import {Plus,ArrowRight,Check,PackageCheck,RefreshCw,Printer} from 'lucide-react';
import {Button,PageHead,Panel,Field,Select,Table,Modal,Notice,Product,Badge,num,ScanInput,Empty} from '../ui.jsx';
import {findItem,norm,newId,docNo} from '../lib/data.js';
import {activeWork} from '../lib/productivity.js';
import {activePickingCart,pickingCartInfo,scanPickingCart,releasePickingCart,batchCandidates,plannedQty,previewCapacityBatches,createCapacityBatches,splitReadyBatch,claimPickBatch,pickCartBatchItem,shortCartBatchTask,replanCartBatch,cancelCapacityBatch,packingCartRows,openPackingKoli,packCartIntoKoli,sealPackingKoli,cancelEmptyPackingKoli,routingDistance} from '../lib/outbound.js';
import {isStorageLocation} from '../lib/locations.js';
import WorkControl from '../WorkControl.jsx';
import {OperationalDetails} from '../OperationalUI.jsx';
import {Picking as LegacyPicking,Packing as LegacyPacking} from './Fulfillment.jsx';
import {printDocument} from '../lib/files.js';
const storeName=(s,id)=>s.stores.find(st=>st.storeId===id)?.storeName||id;
const sum=(rows,key)=>rows.reduce((n,r)=>n+(r[key]||0),0);

function PickTask({s,act,user,b,task,cart}){
 const [location,setLocation]=useState(''),[amount,setAmount]=useState(task.qty-task.pickedQty),[requestId]=useState(newId);
 return <div className="scan-section"><div className="task-context"><span className="eyebrow">{storeName(s,b.storeId)} · {b.id}</span><strong className="mono">{task.location}</strong><Product item={findItem(s,task.sku)} sku={task.sku}/><span>Ambil <b>{num(task.qty-task.pickedQty)} pcs</b> → kereta <b>{cart.cartNo}</b></span></div>
 <Field label="1. Scan lokasi pengambilan"><ScanInput id="cart-pick-location" nextInputId="cart-pick-sku" label="Lokasi pengambilan" placeholder="Scan / foto / input lokasi" allowPhoto submitLabel="Konfirmasi lokasi" onScan={code=>{if(norm(code)!==task.location)throw Error('Lokasi berbeda dari tugas berikutnya');setLocation(norm(code))}}/></Field>
 {location&&<p className="location-selected"><Check size={18}/>{location}</p>}
 <div className="scan-options picking-scan"><Field label="2. Scan SKU"><ScanInput id="cart-pick-sku" label="SKU ke kereta picking" disabled={!location} placeholder="Scan SKU untuk memasukkan barang ke kereta" allowPhoto submitLabel="Masukkan ke kereta" onScan={code=>act(d=>pickCartBatchItem(d,b.id,task.id,{sku:code,location,qty:amount,cartNo:cart.cartNo,requestId},user),'Barang masuk ke kereta')}/></Field><Field label="Qty (pcs)" type="number" min="1" max={task.qty-task.pickedQty} step="1" value={amount} onChange={e=>setAmount(e.target.value)}/></div></div>;
}
export function Picking({s,act,user,navigate}){
 const cart=activePickingCart(s,user),info=cart?pickingCartInfo(s,cart):null,candidates=batchCandidates(s),[registration,setRegistration]=useState(null),[create,setCreate]=useState(null),[store,setStore]=useState(''),[reason,setReason]=useState(null),[busy,setBusy]=useState(false),[legacy,setLegacy]=useState(false);
 const batches=s.pickBatches.filter(b=>b.version===2&&!['FINISHED','CANCELLED'].includes(b.status)),current=batches.find(b=>b.assigneeId===user),task=current?.tasks.find(t=>t.qty>t.pickedQty),work=activeWork(s,user),ready=current&&cart&&current.cartRunId===cart.id&&work?.process==='PICKING'&&work.reference===current.id;
 const ordered=[...batches].filter(b=>!store||b.storeId===store).sort((a,b)=>(s.stores.find(st=>st.storeId===a.storeId)?.priority||0)-(s.stores.find(st=>st.storeId===b.storeId)?.priority||0)||a.createdAt.localeCompare(b.createdAt)||a.id.localeCompare(b.id));
 let preview=[],previewError='';if(create?.pickIds.length){try{preview=previewCapacityBatches(s,create)}catch(e){previewError=e.message}}
 const legacyState={...s,pickBatches:s.pickBatches.filter(b=>b.version!==2),picks:s.picks.filter(p=>p.outboundVersion!==2)};
 async function scan(code){const known=s.cartMasters?.find(c=>c.cartNo===norm(code));if(!known){setRegistration({cartNo:norm(code),capacity:''});return true}return act(d=>scanPickingCart(d,code,user),'Kereta siap. Pilih batch yang akan dikerjakan.');}
 function openCreate(){setCreate({pickIds:candidates.map(p=>p.id),capacity:cart?.capacity||'',startLocation:s.locations.find(isStorageLocation)?.locationCode||''})}
 if(legacy)return <><Button variant="secondary" onClick={()=>setLegacy(false)}>Kembali ke picking kereta</Button><LegacyPicking s={legacyState} act={act} user={user} navigate={navigate} legacyOnly/></>;
 return <><PageHead title="Batch picking" description="Scan kereta → ambil batch per store → scan lokasi dan SKU."><Button variant="secondary" onClick={()=>navigate('packing')}>Buka packing</Button><Button icon={Plus} disabled={!cart||!candidates.length} onClick={openCreate}>Buat batch</Button></PageHead>
 <Panel title={cart?'Kereta aktif':'Mulai dari kereta'} subtitle={cart?`${storeName(s,cart.storeId)||'Belum memilih store'} · ${s.workers.find(w=>w.id===user)?.name}`:'Scan nomor kereta sebelum memilih batch.'}>
 {cart?<div className="outbound-cart-strip"><div><strong className="mono">{cart.cartNo}</strong><span><b>{num(info.used)}</b> / {num(info.capacity)} pcs di kereta · {num(info.reserved)} pcs sisa tugas</span><span className="location-meter"><i style={{width:`${Math.min(100,(info.used+info.reserved)/info.capacity*100)}%`}}/></span></div><Button variant="secondary" disabled={!!current} onClick={()=>act(d=>releasePickingCart(d,user),'Kereta dilepas. Scan kereta baru untuk melanjutkan.')}>Lepas / ganti kereta</Button>{info.used>0&&!current&&<Button icon={ArrowRight} onClick={()=>navigate('packing')}>Lanjut packing</Button>}</div>:<div className="scan-section"><ScanInput label="Kereta picking" placeholder="Scan / foto / input nomor kereta" allowPhoto submitLabel="Gunakan kereta" onScan={scan}/><Button variant="ghost" onClick={()=>setRegistration({cartNo:'',capacity:''})}>Daftarkan / atur kapasitas kereta</Button></div>}
 </Panel>
 {current?<Panel title={current.id} subtitle={`${storeName(s,current.storeId)} · Kereta ${current.cartNo}`} action={<Button variant="ghost" icon={Printer} onClick={()=>printDocument(current.id,['Urutan','Lokasi','SKU','Qty','Diambil'],current.tasks.map((t,i)=>[i+1,t.location,t.sku,t.qty,t.pickedQty]),`${storeName(s,current.storeId)} · Kereta ${current.cartNo}`)}>Cetak batch</Button>}><WorkControl s={s} act={act} user={user} process="PICKING" reference={current.id} disabled={!cart||current.cartRunId!==cart.id}/>{ready&&task?<PickTask key={`${task.id}:${task.pickedQty}`} s={s} act={act} user={user} b={current} task={task} cart={cart}/>:<div className="scan-section"><Notice>Lanjutkan kerja dengan kereta {current.cartNo} untuk menyelesaikan batch.</Notice></div>}
 <OperationalDetails title="Urutan lokasi & progress batch"><Table mobileColumns={[2,1,3,4]} headers={[{label:'Urutan',type:'number'},'Lokasi','SKU / produk',{label:'Target',type:'number'},{label:'Di kereta / diambil',type:'number'},'Status']}>{current.tasks.map((t,i)=><tr key={t.id}><td>{i+1}</td><td className="mono">{t.location}</td><td><Product item={findItem(s,t.sku)}/></td><td>{t.qty}</td><td>{t.pickedQty}</td><td><Badge status={t.status}/>{t.shortQty>0&&<small className="block error-text">Short {t.shortQty} pcs</small>}</td></tr>)}</Table></OperationalDetails><div className="panel-footer"><span>{num(sum(current.tasks,'pickedQty'))} / {num(sum(current.tasks,'qty'))} pcs</span><div className="head-actions"><Button variant="ghost" disabled={!ready||!task} onClick={()=>setReason({kind:'short',batchId:current.id,taskId:task.id,text:''})}>Short-pick tugas</Button><Button icon={RefreshCw} variant="secondary" disabled={!ready} onClick={()=>act(d=>replanCartBatch(d,current.id,user),'Sisa rute batch diperbarui')}>Susun ulang rute</Button><Button variant="ghost" disabled={!ready} onClick={()=>setReason({kind:'cancel',batchId:current.id,text:''})}>Batalkan batch</Button></div></div></Panel>:cart&&<Panel title="Ambil batch" subtitle={`${batches.length} batch menunggu / sedang dikerjakan · ${candidates.length} picking list memiliki qty belum dijadwalkan`}><div className="toolbar"><Field label="Store tujuan"><Select value={store} onChange={e=>setStore(e.target.value)}><option value="">Semua store</option>{s.stores.filter(st=>batches.some(b=>b.storeId===st.storeId)).map(st=><option key={st.storeId} value={st.storeId}>{st.storeName}</option>)}</Select></Field>{!!candidates.length&&<Button icon={Plus} variant="secondary" onClick={openCreate}>Buat batch dari alokasi</Button>}</div>
 <Table mobileColumns={[0,1,2,5]} headers={['Batch','Store',{label:'Qty (pcs)',type:'number'},{label:'Line lokasi',type:'number'},'Operator','Aksi']} empty={!ordered.length} emptyText={candidates.length?'Buat batch dari picking list yang sudah dialokasikan.':'Belum ada batch menunggu. Hasil picking selesai tersedia di Packing.'}>{ordered.map(b=>{const why=b.assigneeId&&b.assigneeId!==user?'Operator lain':cart.storeId&&cart.storeId!==b.storeId?'Store berbeda':sum(b.tasks,'qty')>info.free?'Kapasitas kurang':'';return <tr key={b.id}><td className="mono strong">{b.id}</td><td>{storeName(s,b.storeId)}</td><td>{num(sum(b.tasks,'qty'))}</td><td>{b.tasks.length}</td><td>{s.workers.find(w=>w.id===b.assigneeId)?.name||'Belum diambil'}</td><td>{why?<div><span className="muted">{why}</span>{why==='Kapasitas kurang'&&!b.assigneeId&&info.free>0&&<Button variant="ghost" onClick={()=>act(d=>splitReadyBatch(d,b.id,info.free,user),'Batch dipecah sesuai kapasitas kereta yang tersedia')}>Pecah sesuai kereta</Button>}</div>:<Button disabled={busy} onClick={async()=>{setBusy(true);try{await act(d=>claimPickBatch(d,b.id,user),'Batch dikunci ke operator dan kereta. Mulai picking.')}finally{setBusy(false)}}}>Ambil batch</Button>}</td></tr>})}</Table></Panel>}
 <OperationalDetails title="Panduan rute & kereta"><Notice tone="blue">Batch dipisahkan per store, diurutkan ke lokasi terdekat, lalu dipecah sesuai kapasitas dalam pcs. Rute menggunakan {routingDistance(s).mode}; jarak pada denah belum memperhitungkan jalur lorong. Satu batch dikerjakan satu operator. Kereta kosong setelah seluruh isinya dipacking dapat digunakan kembali.</Notice></OperationalDetails>
 {legacyState.pickBatches.some(b=>!['FINISHED','CANCELLED'].includes(b.status))&&<Button variant="secondary" onClick={()=>setLegacy(true)}>Lanjutkan batch sebelum pembaruan</Button>}
 {registration&&<Modal title="Kereta dan kapasitas" subtitle="Isi kapasitas aktual dalam pcs. Pengaturan tersimpan untuk scan berikutnya." onClose={()=>setRegistration(null)}><form onSubmit={async e=>{e.preventDefault();const next=await act(d=>scanPickingCart(d,registration.cartNo,user,registration.capacity),'Kereta terdaftar dan siap memilih batch');if(next)setRegistration(null)}}><Field label="Nomor kereta" required value={registration.cartNo} onChange={e=>{const code=e.target.value.toUpperCase(),known=s.cartMasters?.find(c=>c.cartNo===code);setRegistration({cartNo:code,capacity:known?.capacity||registration.capacity})}}/><Field label="Kapasitas kereta (pcs)" required type="number" min="1" step="1" value={registration.capacity} onChange={e=>setRegistration({...registration,capacity:e.target.value})}/><div className="modal-actions"><Button variant="secondary" type="button" onClick={()=>setRegistration(null)}>Batal</Button><Button type="submit">Simpan & gunakan kereta</Button></div></form></Modal>}
 {create&&<Modal wide title="Buat batch per kapasitas kereta" subtitle="Setiap batch hanya untuk satu store. Qty di lokasi yang sama bisa dipecah ke beberapa batch." onClose={()=>setCreate(null)}><div className="form-grid"><Field label="Kapasitas rencana per batch (pcs)" type="number" min="1" step="1" max={cart?.capacity} value={create.capacity} onChange={e=>setCreate({...create,capacity:e.target.value})}/><Field label="Lokasi awal"><Select value={create.startLocation} onChange={e=>setCreate({...create,startLocation:e.target.value})}>{s.locations.filter(isStorageLocation).map(l=><option key={l.locationCode}>{l.locationCode}</option>)}</Select></Field></div><div className="batch-options">{candidates.map(p=><label className="scope-option" key={p.id}><input type="checkbox" checked={create.pickIds.includes(p.id)} onChange={e=>setCreate({...create,pickIds:e.target.checked?[...create.pickIds,p.id]:create.pickIds.filter(id=>id!==p.id)})}/><div><strong>{storeName(s,p.storeId)}</strong><small>{p.id} · {num(p.lines.reduce((n,l)=>n+Math.max(0,l.qty-l.pickedQty-plannedQty(s,p.id,l.sku)),0))} pcs belum dijadwalkan</small></div></label>)}</div>{previewError&&<Notice tone="red">{previewError}</Notice>}{!!preview.length&&<Table headers={[{label:'Batch',type:'number'},'Store',{label:'Qty',type:'number'},'Lokasi berurutan']}>{preview.map((b,i)=><tr key={i}><td>{i+1}</td><td>{storeName(s,b.storeId)}</td><td>{num(sum(b.tasks,'qty'))}</td><td>{[...new Set(b.tasks.map(t=>t.location))].join(' → ')}</td></tr>)}</Table>}<div className="modal-actions"><Button variant="secondary" onClick={()=>setCreate(null)}>Batal</Button><Button disabled={busy||!preview.length||!!previewError||Number(create.capacity)>cart?.capacity} onClick={async()=>{setBusy(true);try{const next=await act(d=>createCapacityBatches(d,create,user),`${preview.length} batch dibuat. Pilih batch untuk mulai picking.`);if(next)setCreate(null)}finally{setBusy(false)}}}>Buat {preview.length} batch</Button></div></Modal>}
 {reason&&<Modal title={reason.kind==='short'?'Short-pick tugas ini':'Batalkan batch'} onClose={()=>setReason(null)}><Notice>{reason.kind==='short'?'Hanya sisa qty tugas lokasi ini yang dilepas dari reservasi. Tugas di batch lain tetap berjalan.':'Pastikan semua barang dari batch ini sudah dikembalikan ke lokasi asal. Qty akan tersedia untuk penjadwalan batch kembali.'}</Notice><Field label="Alasan wajib"><textarea value={reason.text} onChange={e=>setReason({...reason,text:e.target.value})}/></Field><div className="modal-actions"><Button variant="secondary" onClick={()=>setReason(null)}>Kembali</Button><Button disabled={!reason.text.trim()} onClick={async()=>{const next=await act(d=>reason.kind==='short'?shortCartBatchTask(d,reason.batchId,reason.taskId,reason.text,user):cancelCapacityBatch(d,reason.batchId,reason.text,user),'Perubahan batch tersimpan');if(next)setReason(null)}}>Konfirmasi</Button></div></Modal>}
 </>;
}

function KoliProcess({s,act,user,k}){
 const [cartNo,setCartNo]=useState(''),[amount,setAmount]=useState(1),[requestId,setRequestId]=useState(newId),work=activeWork(s,user),ready=work?.process==='PACKING'&&work.reference===k.koliNo,rows=packingCartRows(s,{storeId:k.storeId}),cartRows=rows.filter(r=>r.cartNo===cartNo),codes=[...new Set(rows.map(r=>r.cartNo))];
 const products=[...new Set(cartRows.map(r=>r.sku))].map(sku=>({sku,qty:sum(cartRows.filter(r=>r.sku===sku),'remaining'),batches:[...new Set(cartRows.filter(r=>r.sku===sku).map(r=>r.batchId))]}));
 function choose(code){const normalized=norm(code);if(!codes.includes(normalized))throw Error('Kereta tidak memiliki hasil batch picking finish untuk store ini');setCartNo(normalized);setAmount(1);setRequestId(newId());}
 return <Panel title={`Koli ${k.koliNo}`} subtitle={`${storeName(s,k.storeId)} · ${num(sum(k.lines,'qty'))} pcs di koli`}><WorkControl s={s} act={act} user={user} process="PACKING" reference={k.koliNo}/><div className="scan-section"><Field label="1. Kereta asal barang"><ScanInput label="Kereta asal packing" placeholder="Scan / foto / input kereta hasil picking" allowPhoto submitLabel="Buka isi kereta" disabled={!ready} onScan={choose}/></Field><Field label="Atau pilih kereta siap packing"><Select disabled={!ready} value={codes.includes(cartNo)?cartNo:''} onChange={e=>{if(e.target.value)choose(e.target.value)}}><option value="">Pilih kereta</option>{codes.map(code=><option key={code} value={code}>{code} · {num(sum(rows.filter(r=>r.cartNo===code),'remaining'))} pcs</option>)}</Select></Field>
 {!!cartRows.length&&<><div className="outbound-source"><strong>{cartNo}</strong><span>{num(sum(cartRows,'remaining'))} pcs · {[...new Set(cartRows.map(r=>r.batchId))].length} batch siap packing</span></div><div className="scan-options picking-scan"><Field label="2. Scan SKU ke koli"><ScanInput label="SKU ke koli packing" placeholder="Scan SKU hasil picking finish" allowPhoto submitLabel="Masukkan ke koli" disabled={!ready} onScan={async code=>{const next=await act(d=>packCartIntoKoli(d,{koliNo:k.koliNo,cartNo,sku:code,qty:amount,requestId},user),'Barang masuk ke koli; sisa kereta diperbarui');if(next){setRequestId(newId());setAmount(1)}return next}}/></Field><Field label="Qty ke koli (pcs)" type="number" min="1" step="1" value={amount} onChange={e=>setAmount(e.target.value)}/></div><small>Qty dapat diambil sebagian. Jika SKU berasal dari beberapa batch, sistem memakai batch yang dibuat lebih dahulu.</small><Table mobileColumns={[0,1,3]} headers={['SKU / produk',{label:'Sisa di kereta',type:'number'},'Batch asal','Aksi']}>{products.map(r=><tr key={r.sku}><td><Product item={findItem(s,r.sku)}/></td><td>{num(r.qty)}</td><td>{r.batches.join(', ')}</td><td><Button variant="ghost" onClick={()=>setAmount(r.qty)}>Isi qty {num(r.qty)}</Button></td></tr>)}</Table></>}
 {!rows.length&&<Notice tone="blue">Semua hasil picking finish untuk store ini telah masuk koli. Seal koli atau tunggu batch berikutnya selesai.</Notice>}</div>
 <OperationalDetails title={`Isi koli · ${k.lines.length} line asal batch`}><Table mobileColumns={[0,1,2,3]} headers={['SKU / produk',{label:'Qty',type:'number'},'Batch asal','Kereta','Lokasi asal']} empty={!k.lines.length}>{k.lines.map(l=><tr key={l.taskId}><td><Product item={findItem(s,l.sku)}/></td><td>{num(l.qty)}</td><td className="mono">{l.batchId}</td><td>{l.cartNo}</td><td>{l.location}</td></tr>)}</Table></OperationalDetails><div className="panel-footer"><span><b>{num(sum(k.lines,'qty'))} pcs</b> · {[...new Set(k.lines.map(l=>l.batchId))].length} batch dalam koli</span><div className="head-actions">{!k.lines.length&&<Button variant="ghost" onClick={()=>act(d=>cancelEmptyPackingKoli(d,k.koliNo,user),'Koli kosong dibatalkan')}>Batalkan koli kosong</Button>}<Button icon={Printer} variant="secondary" disabled={!k.lines.length} onClick={()=>printDocument(k.koliNo,['SKU','Qty','Batch','Kereta'],k.lines.map(l=>[l.sku,l.qty,l.batchId,l.cartNo]),`Tujuan ${storeName(s,k.storeId)}`)}>Cetak isi koli</Button><Button icon={PackageCheck} disabled={!ready||!k.lines.length} onClick={()=>act(d=>sealPackingKoli(d,k.koliNo,user),'Koli disegel; surat jalan siap dikirim')}>Seal koli & buat surat jalan</Button></div></div></Panel>;
}
export function Packing({s,act,user,navigate}){
 const rows=packingCartRows(s),active=s.packingKolis?.find(k=>k.status==='OPEN'&&k.ownerId===user),stores=s.stores.filter(st=>rows.some(r=>r.storeId===st.storeId)),[selected,setSelected]=useState(''),[legacy,setLegacy]=useState(false),storeId=stores.some(st=>st.storeId===selected)?selected:stores[0]?.storeId||'';
 const legacyState={...s,picks:s.picks.filter(p=>p.outboundVersion!==2)};
 if(legacy)return <><Button variant="secondary" onClick={()=>setLegacy(false)}>Kembali ke packing koli</Button><LegacyPacking s={legacyState} act={act} user={user} navigate={navigate}/></>;
 return <><PageHead title="Packing per koli" description="Satu koli dapat berisi seluruh atau sebagian beberapa batch untuk store yang sama."><Button variant="secondary" onClick={()=>navigate('picking')}>Buka picking</Button><Button variant="secondary" onClick={()=>navigate('shipping')}>Buka pengiriman</Button></PageHead>
 {active?<KoliProcess key={active.koliNo} s={s} act={act} user={user} k={active}/>:<Panel title="Mulai koli packing" subtitle={`${num(sum(rows,'remaining'))} pcs hasil batch picking finish`}>
 {rows.length?<div className="scan-section"><Field label="Store tujuan"><Select value={storeId} onChange={e=>setSelected(e.target.value)}>{stores.map(st=><option key={st.storeId} value={st.storeId}>{st.storeName}</option>)}</Select></Field><Field label="Nomor koli outbound"><ScanInput label="Nomor koli outbound" placeholder="Scan / foto / input nomor koli" allowPhoto submitLabel="Buka koli & mulai" onScan={code=>act(d=>openPackingKoli(d,code,storeId,user),'Koli siap diisi')}/></Field><Button icon={Plus} variant="secondary" onClick={()=>act(d=>openPackingKoli(d,docNo(d,'KO'),storeId,user),'Nomor koli dibuat dan siap diisi')}>Buat nomor koli otomatis</Button></div>:<Empty title="Belum ada batch picking finish" description="Selesaikan seluruh tugas dalam batch untuk memindahkan isinya ke koli packing." action={<Button onClick={()=>navigate('picking')}>Buka picking</Button>}/>}
 </Panel>}
 {legacyState.picks.some(p=>!['CANCELLED','SHIPPED','PACKED'].includes(p.status)&&p.lines.some(l=>l.qty>0&&l.pickedQty===l.qty))&&<Button variant="secondary" onClick={()=>setLegacy(true)}>Selesaikan packing sebelum pembaruan</Button>}
 </>;
}
