import React,{useState} from 'react';
import {ArrowDownToLine,Package,Boxes,Truck,ArrowUpRight,ArrowRight,ClipboardCheck,Clock,Activity,AlertTriangle,BarChart3,CalendarDays,RefreshCw} from 'lucide-react';
import {Button,PageHead,Panel,Table,Product,Badge,num,Empty,time,Stat,Select} from '../ui.jsx';
import {available,reserved,findItem} from '../lib/data.js';
import Productivity from './Productivity.jsx';
import WarehouseUtilization from './WarehouseUtilization.jsx';
import {calculateSOQ} from '../../web/js/lib/allocation.js';
export default function Dashboard({s,navigate}){const [period,setPeriod]=useState('TODAY'),[store,setStore]=useState('ALL');const midnight=new Date();midnight.setHours(0,0,0,0);const cutoff=period==='TODAY'?midnight.getTime():Date.now()-7*86400000;const stores=s.stores.filter(st=>store==='ALL'||st.storeId===store);const totalStock=s.stock.reduce((n,r)=>n+r.qty,0),totalAvailable=s.items.reduce((n,i)=>n+available(s,i.sku),0),totalReserved=s.items.reduce((n,i)=>n+reserved(s,i.sku),0),staging=s.stock.filter(r=>r.locationCode[0]==='S').reduce((n,r)=>n+r.qty,0),orders=s.orders.filter(o=>(store==='ALL'||o.storeId===store)&&new Date(o.shippedAt||o.createdAt).getTime()>=cutoff),pending=s.approvals.filter(a=>a.status.startsWith('PENDING'));
const shortage=s.items.map(i=>{let soq=0,review=0;for(const st of stores){const k=`${st.storeId}_${i.sku}`,c=s.classification[k]?.class,ss=s.safety[`${st.storeId}_${c}`];const l=calculateSOQ({dad:s.demand[k]?.dad,oc:st.orderCycleDays,lt:st.leadTimeDays,ssd:ss?.ssDemandDays,sslt:ss?.ssLeadTimeDays,oh:s.oh[k],od:s.od[k],itemClass:c});soq+=l.soq;review+=l.needsManualReview?1:0}return {...i,soq,review,available:available(s,i.sku)}}).filter(i=>i.soq>i.available).sort((a,b)=>(b.soq-b.available)-(a.soq-a.available));const coverage=stores.map(st=>{const vals=s.items.map(i=>({dad:s.demand[`${st.storeId}_${i.sku}`]?.dad,oh:s.oh[`${st.storeId}_${i.sku}`],od:s.od[`${st.storeId}_${i.sku}`]})).filter(v=>v.dad>0&&v.oh!=null&&v.od!=null),dad=vals.reduce((n,v)=>n+v.dad,0);return {...st,coverage:dad?vals.reduce((n,v)=>n+v.oh+v.od,0)/dad:0}}).sort((a,b)=>a.coverage-b.coverage);
const zoneData=[['Penyimpanan umum',s.stock.filter(r=>/^[A-P]/.test(r.locationCode)).reduce((n,r)=>n+r.qty,0),'#47739a'],['Staging',staging,'#eeab49'],['Karantina',s.stock.filter(r=>r.locationCode[0]==='Q').reduce((n,r)=>n+r.qty,0),'#d86964'],['Retur',s.stock.filter(r=>r.locationCode[0]==='R').reduce((n,r)=>n+r.qty,0),'#8d86bc']];const movements=s.movements.filter(m=>new Date(m.createdAt).getTime()>=cutoff).slice(-5).reverse();
return <><PageHead eyebrow="DISTRIBUTION CENTER · TIGALAPAN INDONESIA" title="Ringkasan gudang" description="Pantau pergerakan barang dan pekerjaan yang perlu ditindaklanjuti."><div className="date-control"><CalendarDays size={17}/><Select aria-label="Periode dashboard" value={period} onChange={e=>setPeriod(e.target.value)}><option value="TODAY">Hari ini</option><option value="WEEK">7 hari terakhir</option></Select></div><Button icon={ArrowDownToLine} onClick={()=>navigate('receiving')}>Terima kiriman</Button></PageHead>
<WarehouseUtilization s={s} actionLabel="Buka Location control" onOpenLayout={()=>navigate('location-control')}/>
<div className="stats"><Stat label="Stok tersedia DC" icon={Boxes} value={totalAvailable} detail={`${num(s.items.length)} SKU · ${s.stores.length} cabang tujuan`} accent/><Stat label="Stok direservasi" icon={Package} value={totalReserved} detail={`${s.allocations.filter(a=>a.status==='CONFIRMED').length} alokasi terkonfirmasi`}/><Stat label="Menunggu putaway" icon={ArrowDownToLine} value={staging} detail={`${s.stock.filter(r=>r.locationCode[0]==='S'&&r.qty>0).length} SKU di area staging`}/><Stat label="Pengiriman selesai" icon={Truck} value={orders.filter(o=>o.status==='SHIPPED').length} unit="DO" detail={`${num(orders.filter(o=>o.status==='SHIPPED').reduce((n,o)=>n+o.lines.reduce((m,l)=>m+l.qty,0),0))} pcs terkirim pada periode ini`}/></div>
<Productivity s={s} cutoff={cutoff}/><div className="dashboard-columns"><div className="dashboard-main"><Panel title="Alur operasional" subtitle="Dari penerimaan sampai barang diberangkatkan" action={<span className="live-label">Pembaruan otomatis</span>}><div className="flow-cards">{[['receiving',ArrowDownToLine,'Receiving',s.kolis.filter(k=>['PENDING','CHECKING'].includes(k.status)).length,'koli perlu diperiksa'],['putaway',Boxes,'Putaway',s.stock.filter(r=>r.locationCode[0]==='S'&&r.qty>0).length,'SKU menunggu'],['picking',ClipboardCheck,'Batch picking',s.picks.filter(p=>!['SHIPPED','CANCELLED'].includes(p.status)).length,'picking list aktif'],['shipping',Truck,'Shipping',s.orders.filter(o=>o.status==='READY'&&(store==='ALL'||o.storeId===store)).length,'DO siap berangkat']].map(([id,Icon,label,value,unit],i)=><button key={id} className="flow-card" onClick={()=>navigate(id)}><div><span className={`flow-icon step-${i}`}><Icon size={21}/></span><ArrowUpRight size={16}/></div><h3>{label}</h3><strong>{value}</strong><small>{unit}</small></button>)}</div></Panel>
<Panel title="Stok yang perlu perhatian" subtitle={`${shortage.length} SKU dengan kebutuhan di atas stok tersedia`} action={<Button variant="ghost" icon={ArrowRight} onClick={()=>navigate('allocation')}>Lihat alokasi</Button>}><div className="toolbar subtle"><Select aria-label="Filter cabang dashboard" value={store} onChange={e=>setStore(e.target.value)}><option value="ALL">Seluruh cabang</option>{s.stores.map(st=><option value={st.storeId} key={st.storeId}>{st.storeName}</option>)}</Select><span className="legend"><span className="legend-square amber-bg"/>Kebutuhan belum terpenuhi</span></div><Table pageSize={5} resetKey={store} headers={['Produk / SKU',{label:'Tersedia',type:'number'},{label:'Kebutuhan',type:'number'},{label:'Kekurangan',type:'number'}]} empty={!shortage.length}>{shortage.map(i=><tr key={i.sku}><td><Product item={i}/></td><td className="number" data-filter-value={i.available}>{num(i.available)}</td><td className="number" data-filter-value={i.soq}>{num(i.soq)}</td><td className="number"><span className="shortage-tag">{num(i.soq-i.available)} pcs</span></td></tr>)}</Table><div className="table-note">{s.items.filter(i=>available(s,i.sku)===0).length} SKU stok kosong · Perhitungan menggunakan data perangkat ini</div></Panel>
<Panel title="Aktivitas terakhir" subtitle="Riwayat pergerakan barang pada periode terpilih" action={<Button variant="ghost" onClick={()=>navigate('activity')}>Lihat semua <ArrowRight size={15}/></Button>}>{movements.length?<div className="activity-list">{movements.map(m=><div className="activity-row" key={m.movementId}><span className="activity-icon"><Activity size={17}/></span><div><strong>{m.type} <span className="mono">{m.sku}</span></strong><span>{m.fromLocation||'Masuk'} → {m.toLocation||'Keluar'} · {m.refDoc}</span></div><div><strong>{m.qty} pcs</strong><small>{time(m.createdAt)}</small></div></div>)}</div>:<div className="quiet-empty"><Activity size={22}/><div><strong>Belum ada pergerakan barang</strong><span>Mulai receiving atau putaway untuk mencatat aktivitas pertama.</span></div><Button variant="ghost" onClick={()=>navigate('putaway')}>Mulai <ArrowRight size={16}/></Button></div>}</Panel></div>
<div className="dashboard-aside"><Panel title="Perlu tindakan" action={<span className="count">{pending.length+s.queue.length}</span>}><button className="action-item" onClick={()=>navigate('approvals')}><span className="action-icon amber-bg"><ShieldIcon/></span><div><strong>Persetujuan tertunda</strong><span>{pending.filter(a=>a.status==='PENDING_SPV').length} SPV · {pending.filter(a=>a.status==='PENDING_MANAGER').length} Manager</span></div><b>{pending.length}</b><ArrowRight size={15}/></button><button className="action-item" onClick={()=>navigate('sync')}><span className="action-icon blue-bg"><RefreshCw size={18}/></span><div><strong>Antrean integrasi</strong><span>Supabase, Moka & Mini ERP</span></div><b>{s.queue.length}</b><ArrowRight size={15}/></button><button className="action-item" onClick={()=>navigate('opname')}><span className="action-icon red-bg"><ClipboardCheck size={18}/></span><div><strong>Prioritas cycle count</strong><span>Tindak lanjut short-pick</span></div><b>{s.counts.filter(c=>c.status==='PRIORITY').length}</b><ArrowRight size={15}/></button></Panel>
<Panel title="Komposisi stok fisik" subtitle="Jumlah barang per area gudang"><div className="stock-composition"><strong>{num(totalStock)} <small>pcs</small></strong><div className="stacked-bar" role="img" aria-label="Proporsi stok fisik per zona">{zoneData.map(([name,value,color])=><div key={name} title={`${name}: ${value} pcs`} style={{width:`${totalStock?value/totalStock*100:0}%`,background:color}}/>)}</div>{zoneData.map(([name,value,color])=><div className="zone-legend" key={name}><span><i style={{background:color}}/>{name}</span><b>{num(value)}</b></div>)}<small className="muted">Reservasi merupakan bagian dari stok penyimpanan umum.</small></div></Panel>
<Panel title="Coverage cabang" subtitle="Cabang dengan cakupan stok terendah"><div className="coverage-list">{coverage.slice(0,5).map((st,i)=><div key={st.storeId}><span className="coverage-rank">{String(i+1).padStart(2,'0')}</span><div><strong>{st.storeName}</strong><div className="coverage-track"><span style={{width:`${Math.min(100,st.coverage/14*100)}%`}}/></div></div><b>{num(st.coverage)}<small>hari</small></b></div>)}</div><div className="table-note">Σ (OH + OD) ÷ Σ DAD · SKU dengan DAD positif</div></Panel><div className="allocation-callout"><BarChart3 size={24}/><strong>Rencanakan distribusi berikutnya</strong><p>Simulasikan kebutuhan seluruh cabang sebelum mengunci stok.</p><Button variant="secondary" onClick={()=>navigate('allocation')}>Buka alokasi <ArrowRight size={16}/></Button></div></div></div></>}
function ShieldIcon(){return <ClipboardCheck size={18}/>}
