import React,{useEffect,useState} from 'react';
import {Download,RefreshCw,ArrowRight} from 'lucide-react';
import {PageHead,Panel,Button,Notice,Table,Select,Field,time} from '../ui.jsx';
import {download} from '../lib/files.js';
import {planResiImport,applyResiSnapshot,applyMokaStock,recordIntegrationReceipt} from '../lib/integration.js';
const labels={WAITING_CONFIGURATION:'Menunggu konfigurasi',WAITING_REMOTE:'Diterima outbox · belum diterapkan',SYNCED:'Tersinkron',FAILED:'Gagal di tujuan',UNKNOWN:'Perlu cek status',SENDING:'Sedang dikirim'};
export default function Integrations({s,act,notify,user}){
 const [config,setConfig]=useState(null),[busy,setBusy]=useState(false),[target,setTarget]=useState('ALL'),[resi,setResi]=useState(null),[stock,setStock]=useState(null),[storeId,setStore]=useState('');
 async function api(path,body){const r=await fetch('/api/integrations/'+path,{cache:'no-store',...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});if(r.status===401){location.assign('/login');throw Error('Sesi berakhir. Masuk kembali.')}const json=await r.json();if(!r.ok)throw Error(json.error||'Koneksi belum berhasil.');return json;}
 async function run(fn){setBusy(true);try{await fn()}catch(e){notify(e.message,'error')}finally{setBusy(false)}}
 useEffect(()=>{api('status').then(setConfig).catch(()=>{})},[]);
 const plan=resi?planResiImport(s,resi):null,rows=s.queue.filter(q=>target==='ALL'||q.target===target);
 async function send(q,action){
  let locked;const ok=await act(d=>{const current=d.queue.find(x=>x.id===q.id);if(!current||current.status==='SYNCED')throw Error('Event sudah selesai atau tidak ditemukan.');if(action==='submit'&&['SENDING','UNKNOWN','WAITING_REMOTE'].includes(current.status))throw Error('Periksa status tujuan sebelum mengirim ulang.');current.attempts=(current.attempts||0)+(action==='submit'?1:0);current.status=action==='submit'?'SENDING':current.status;locked=structuredClone(current)},action==='submit'?'Mengirim event dengan ID tetap':'Memeriksa tanda terima tujuan');if(!ok)return;
  try{const result=await api('outbox',{action,event:locked});await act(d=>recordIntegrationReceipt(d,q.id,result),result.status==='APPLIED'?'Tujuan mengonfirmasi event telah diterapkan':'Status tujuan diperbarui; antrean belum tentu tersinkron')}
  catch(e){await act(d=>{const current=d.queue.find(x=>x.id===q.id);if(current&&current.status!=='SYNCED'){current.status='UNKNOWN';current.lastError=e.message}},'Event dipertahankan untuk pemeriksaan status');throw e;}
 }
 return <><PageHead title="Integrasi & sinkronisasi" description="Mini ERP (Supabase) ↔ WMS ↔ API Moka POS"><Button variant="secondary" disabled={busy} icon={RefreshCw} onClick={()=>run(async()=>{setConfig(await api('status'));notify('Status konfigurasi server diperbarui')})}>Periksa konfigurasi</Button></PageHead>
 <Notice>{config?.enabled?'Konektor server diaktifkan. Status tersinkron hanya diberikan setelah ada bukti penerapan dari sistem tujuan.':'Koneksi langsung belum aktif. Akses Supabase, pemetaan resi, token Moka, dan pemetaan outlet perlu dilengkapi di server.'} Data stok fisik WMS masih tersimpan per browser.</Notice>
 <div className="integration-grid"><Panel title="Mini ERP → WMS" subtitle="Resi, vendor, jumlah koli, SKU dan Qty"><div className="form-pad"><p>{config?.miniErp?'Konfigurasi sumber tersedia; koneksi belum diuji sampai penarikan berhasil.':'Menunggu URL Supabase dan RPC sumber resi.'}</p><Button disabled={busy||!config?.enabled||!config?.miniErp} onClick={()=>run(async()=>{setResi(await api('resi'));notify('Snapshot resi diterima; periksa sebelum mengimpor')})}>Ambil resi Mini ERP</Button></div></Panel>
 <Panel title="WMS → Mini ERP / Moka" subtitle="Antrean persisten dan tanda terima tujuan"><div className="form-pad"><p>{config?.outbox?'Konfigurasi outbox tersedia. Penerimaan outbox belum berarti stok Moka berubah.':'Menunggu RPC outbox idempoten pada Supabase.'}</p><p className="muted">Hasil penerimaan, Putaway, Shipping, koreksi dan retur dikirim sebagai event dengan ID tetap. Proses transfer Moka menunggu pemetaan dan verifikasi API.</p></div></Panel>
 <Panel title="Moka POS → WMS" subtitle="Stok cabang dan identitas SKU / outlet"><div className="form-pad"><p>{config?.moka?'Konfigurasi token tersedia; tarik data untuk memeriksa akses.':'Menunggu token API dan pemetaan outlet.'}</p><Field label="Cabang / outlet"><Select value={storeId} onChange={e=>{setStore(e.target.value);setStock(null)}}><option value="">Pilih cabang</option>{(config?.outlets||[]).map(o=><option key={o.storeId} value={o.storeId}>{s.stores.find(st=>st.storeId===o.storeId)?.storeName||o.storeId} · outlet {o.outletId}</option>)}</Select></Field><Button disabled={busy||!storeId||!config?.enabled||!config?.moka} onClick={()=>run(async()=>{setStock(await api('moka-stock?storeId='+encodeURIComponent(storeId)));notify('Stok Moka diterima untuk ditinjau')})}>Ambil stok Moka</Button></div></Panel></div>
 {plan&&<Panel title="Pratinjau resi Mini ERP" subtitle={`${plan.groups.length} resi baru · ${plan.rows.length} baris baru · ${plan.skipped} baris resi yang sudah ada`} action={<Button disabled={busy||!plan.rows.length||!!plan.errors.length} icon={ArrowRight} onClick={()=>run(async()=>{const ok=await act(d=>applyResiSnapshot(d,resi,user),'Resi Mini ERP siap diproses di Receiving');if(ok)setResi(null)})}>Impor resi ke Receiving</Button>}>
 {!!plan.errors.length&&<Notice tone="red">{plan.errors[0]}</Notice>}<Table headers={['Nomor resi','Vendor','Ekspedisi','Nomor koli','SKU','PO',{label:'Qty',type:'number'}]} empty={!plan.rows.length}>{plan.rows.map((r,i)=><tr key={i}><td>{r.externalResiNo}</td><td>{r.vendorName}</td><td>{r.expedition}</td><td>{r.vendorKoliNo}</td><td>{r.sku}</td><td>{r.poNumber}</td><td>{r.qty}</td></tr>)}</Table></Panel>}
 {stock&&<Panel title={`Pratinjau stok Moka · ${stock.storeId}`} subtitle={`Outlet ${stock.outletId} · ${stock.fetchedAt}`} action={<Button disabled={busy||stock.storeId==='DC'} onClick={()=>run(async()=>{const ok=await act(d=>applyMokaStock(d,stock),'Saldo cabang diperbarui; stok fisik DC tetap mengikuti transaksi gudang');if(ok)setStock(null)})}>Terapkan saldo cabang</Button>}><Notice>SKU dicocokkan secara tepat. SKU kosong, ganda, belum dikenal, atau snapshot tidak lengkap harus diperbaiki terlebih dahulu.</Notice><Table headers={['SKU','Item Moka','Variant Moka',{label:'Qty',type:'number'}]} empty={!stock.rows.length}>{stock.rows.map((r,i)=><tr key={i}><td>{r.sku||'Belum dipetakan'}</td><td>{r.itemId}</td><td>{r.variantId}</td><td>{r.qty}</td></tr>)}</Table></Panel>}
 <Panel title="Antrean transaksi" action={<Button icon={Download} variant="secondary" onClick={()=>download('wms-integration-queue.json',JSON.stringify(s.queue,null,2),'application/json')}>Ekspor antrean</Button>}><div className="toolbar"><Select aria-label="Filter tujuan integrasi" value={target} onChange={e=>setTarget(e.target.value)}><option value="ALL">Semua tujuan</option><option value="MINI_ERP">Mini ERP</option><option value="MOKA">Moka POS</option></Select></div><Table resetKey={target} headers={['Waktu','Tujuan','Peristiwa','Referensi','Status','Bukti tujuan',{label:'Percobaan',type:'number'},'Aksi']} empty={!rows.length}>{rows.slice().reverse().map(q=><tr key={q.id}><td>{time(q.createdAt)}</td><td>{q.target}</td><td>{q.event}</td><td>{q.payload.externalResiNo||q.payload.reference||q.payload.sku}</td><td>{labels[q.status]||q.status}{q.lastError&&<p className="error-text">{q.lastError}</p>}</td><td>{q.externalId||'—'}</td><td>{q.attempts}</td><td>{q.status!=='SYNCED'&&<Button variant="ghost" disabled={busy||!config?.enabled||!config?.outbox} onClick={()=>run(()=>send(q,['SENDING','UNKNOWN','WAITING_REMOTE'].includes(q.status)?'status':'submit'))}>{['SENDING','UNKNOWN','WAITING_REMOTE'].includes(q.status)?'Cek status':'Kirim event'}</Button>}</td></tr>)}</Table></Panel>
 <Panel title="Cadangan data perangkat"><div className="form-pad"><Button variant="secondary" icon={Download} onClick={()=>download('wms38-backup.json',JSON.stringify(s,null,2),'application/json')}>Unduh semua data WMS</Button></div></Panel></>;
}
