import React,{useState} from 'react';
import {MapPin,Pencil,Settings2,Layers} from 'lucide-react';
import {Button,PageHead,Panel,Table,SearchBox,Field,Select,Modal,Notice,Product,num,Empty} from '../ui.jsx';
import {isStorageLocation,locationCapacity,locationAssignments,saveLocationCapacity} from '../lib/locations.js';
import {AbcBadge,LocationMappingEditor} from './LocationMapping.jsx';
import Rack3D from './Rack3D.jsx';
import WarehouseLayoutEditor from './WarehouseLayoutEditor.jsx';
import WarehouseUtilization from './WarehouseUtilization.jsx';

export function LocationMap({s,query='',abc='',zone='',mode='mapping',onSelect}){
 const locations=s.locations.filter(isStorageLocation).sort((a,b)=>a.locationCode.localeCompare(b.locationCode));
 const shown=locations.flatMap(l=>{
  const assigned=locationAssignments(s,l.locationCode);
  const entries=mode==='stock'?s.stock.filter(r=>r.locationCode===l.locationCode&&r.qty>0).map(r=>({item:s.items.find(i=>i.sku===r.sku)||{sku:r.sku},qty:r.qty})):assigned;
  const classes=[...new Set(entries.map(r=>r.item.abcClass||'none'))].sort();
  if(zone&&l.zone!==zone||abc&&!entries.some(r=>(r.item.abcClass||'none')===abc))return [];
  if(query&&!`${l.locationCode} ${entries.map(r=>`${r.item.sku} ${r.item.itemName}`).join(' ')}`.toLowerCase().includes(query.toLowerCase()))return [];
  return [{...l,...locationCapacity(s,l.locationCode),entries,classes}];
 });
 const racks=[...new Set(shown.map(l=>l.zone+l.rack))];
 if(!shown.length)return <Empty title="Tidak ada lokasi sesuai filter" description="Ubah pencarian, zona, atau kelas ABC."/>;
 return <div className="abc-map-racks">{racks.map(rack=><section className="abc-rack" key={rack}><header><Layers size={18}/><h3>Rak {rack}</h3><span>{shown.filter(l=>l.zone+l.rack===rack).length} lokasi</span></header><div className="abc-slot-grid">{shown.filter(l=>l.zone+l.rack===rack).map(l=><button key={l.code} className={`abc-slot abc-slot-${l.classes.length===1?l.classes[0]:l.classes.length?'mixed':'empty'} ${l.blocked||l.free===0?'slot-full':''}`} onClick={()=>onSelect?.(l.code)} aria-label={`Lokasi ${l.code}, ${l.entries.length} SKU, ${l.used} pcs, ${l.status}`}><strong>{l.code}</strong><span className="abc-slot-classes">{l.classes.map(c=><AbcBadge key={c} value={c==='none'?'':c}/>)}{!l.classes.length&&<span>{mode==='stock'?'Kosong':'Belum dipetakan'}</span>}</span><span>{l.entries.length} SKU {mode==='stock'?'tersimpan':'dipetakan'} · {num(l.used)} pcs</span><small>{l.blocked?'Penuh sementara':l.capacity==null?'Kapasitas belum diatur':`${num(l.used)} / ${num(l.capacity)} pcs`}</small><span className="location-meter" aria-hidden="true"><i style={{width:l.capacity?`${Math.min(100,l.used/l.capacity*100)}%`:'0%'}}/></span></button>)}</div></section>)}</div>;
}
export default function LocationControl({s,act,accountId,navigate,initial='mapping'}){
 const [tab,setTab]=useState(initial),[query,setQuery]=useState(''),[abc,setAbc]=useState(''),[zone,setZone]=useState(''),[mode,setMode]=useState('mapping'),[view,setView]=useState('3d'),[editing,setEditing]=useState(null),[selected,setSelected]=useState(''),[capacity,setCapacity]=useState(null),[fullMap,setFullMap]=useState(false);
 const locations=s.locations.filter(isStorageLocation),search=query.toLowerCase();
 const items=s.items.filter(i=>(!abc||(i.abcClass||'none')===abc)&&(!zone||[i.primaryLocation,...(i.reserveLocations||[])].some(l=>l?.startsWith(zone)))&&`${i.sku} ${i.itemName} ${i.primaryLocation} ${(i.reserveLocations||[]).join(' ')}`.toLowerCase().includes(search));
 const locs=locations.filter(l=>(!zone||l.zone===zone)&&`${l.locationCode} ${locationAssignments(s,l.locationCode).map(r=>`${r.item.sku} ${r.item.itemName}`).join(' ')}`.toLowerCase().includes(search)&&(!abc||locationAssignments(s,l.locationCode).some(r=>(r.item.abcClass||'none')===abc)));
 const detail=selected?locationCapacity(s,selected):null;
 function editCapacity(code){const l=s.locations.find(l=>l.locationCode===code);setCapacity({locationCode:code,capacity:l.capacity??'',putawayBlocked:l.putawayBlocked===true,expected:{capacity:l.capacity??null,putawayBlocked:l.putawayBlocked===true}});setSelected('');}
 return <><PageHead eyebrow="KONTROL GUDANG" title="Location control" description="Petakan tujuan penyimpanan SKU dan pantau kapasitas lokasi."><Button variant="secondary" onClick={()=>navigate?.('reports')}>Buka laporan</Button><Button icon={MapPin} onClick={()=>setEditing({selectable:true,item:s.items[0]})} disabled={!s.items.length}>Mapping SKU</Button></PageHead>
 <WarehouseUtilization s={s} onOpenLayout={()=>setTab('layout')}/>
 <div className="location-summary">{[['SKU dipetakan',s.items.filter(i=>i.primaryLocation).length,`${s.items.length} SKU total`],['Relasi reserve',s.items.reduce((n,i)=>n+(i.reserveLocations||[]).length,0),'Beberapa reserve per SKU'],['Lokasi penyimpanan',locations.length,'Zona A–P'],['Lokasi penuh',locations.filter(l=>{const c=locationCapacity(s,l.locationCode);return c.blocked||c.free===0}).length,'Termasuk penuh sementara']].map(([label,value,desc])=><div key={label}><span>{label}</span><strong>{num(value)}</strong><small>{desc}</small></div>)}</div>
 <div className="tabs">{[['mapping','Mapping SKU'],['map','Peta ABC 3D'],['layout','Atur tata letak'],['capacity','Kapasitas lokasi']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {tab==='layout'?<Panel><WarehouseLayoutEditor s={s} act={act} accountId={accountId} onView3D={()=>setTab('map')}/></Panel>:<Panel><div className="location-controls"><SearchBox value={query} onChange={setQuery} placeholder="Cari SKU, produk, atau lokasi…"/><Field label="Kelas ABC"><Select value={abc} onChange={e=>setAbc(e.target.value)}><option value="">Semua kelas</option>{['A','B','C'].map(c=><option key={c} value={c}>Kelas {c}</option>)}<option value="none">Belum diisi</option></Select></Field><Field label="Zona"><Select value={zone} onChange={e=>setZone(e.target.value)}><option value="">Semua zona</option>{[...new Set(locations.map(l=>l.zone))].sort().map(z=><option key={z} value={z}>Zona {z}</option>)}</Select></Field>{(query||abc||zone)&&<Button variant="ghost" onClick={()=>{setQuery('');setAbc('');setZone('')}}>Hapus filter</Button>}</div>
 {tab==='mapping'&&<Table resetKey={`${query}|${abc}|${zone}`} exportFilename="mapping-lokasi-sku.csv" headers={['SKU / produk','ABC gudang','Lokasi utama','Lokasi reserve',{label:'Jumlah reserve',type:'number'},'Status mapping','Aksi']} empty={!items.length}>{items.map(i=><tr key={i.sku}><td><Product item={i}/></td><td><AbcBadge value={i.abcClass}/></td><td className="mono strong">{i.primaryLocation||'Belum dipetakan'}</td><td>{(i.reserveLocations||[]).join(', ')||'Belum dipetakan'}</td><td>{i.reserveLocations?.length||0}</td><td>{!i.primaryLocation?'Perlu lokasi utama':!i.reserveLocations?.length?'Perlu reserve':!i.abcClass?'Perlu kelas ABC':'Lengkap'}</td><td><Button variant="ghost" icon={Pencil} onClick={()=>setEditing({item:i})}>Mapping</Button></td></tr>)}</Table>}
 {tab==='map'&&<><div className="abc-map-tools"><Field label="Tampilan rak"><Select value={view} onChange={e=>setView(e.target.value)}><option value="3d">Rak 3D</option><option value="2d">Daftar lokasi 2D</option></Select></Field><Field label="Isi peta"><Select value={mode} onChange={e=>setMode(e.target.value)}><option value="mapping">Mapping lokasi</option><option value="stock">Stok fisik</option></Select></Field><div className="abc-legend"><span>ABC gudang:</span>{['A','B','C'].map(c=><AbcBadge key={c} value={c}/>)}</div></div><p className="abc-map-caption">{mode==='mapping'?'Menampilkan rencana penempatan utama dan reserve.':'Menampilkan SKU yang sudah tersimpan di lokasi.'} Warna mengikuti kelas ABC pada Master SKU. Klik lokasi untuk melihat rinciannya. Tata letak mengikuti posisi dan ukuran rak tersimpan; isi tiap bin mengikuti Master SKU.</p>{view==='3d'?<Rack3D s={s} query={query} abc={abc} zone={zone} mode={mode} onSelect={setSelected} onExpand={()=>setFullMap(true)}/>:<LocationMap s={s} query={query} abc={abc} zone={zone} mode={mode} onSelect={setSelected}/>}</>}
 {tab==='capacity'&&<Table resetKey={`${query}|${abc}|${zone}`} exportFilename="kapasitas-lokasi.csv" headers={['Lokasi','Zona',{label:'SKU dipetakan',type:'number'},{label:'Isi (pcs)',type:'number'},{label:'Kapasitas (pcs)',type:'number'},{label:'Sisa (pcs)',type:'number'},'Status','Aksi']} empty={!locs.length}>{locs.map(l=>{const c=locationCapacity(s,l.locationCode);return <tr key={c.code}><td className="mono strong">{c.code}</td><td>{l.zone}</td><td>{locationAssignments(s,c.code).length}</td><td>{num(c.used)}</td><td data-filter-value={c.capacity??''}>{c.capacity==null?'Belum diatur':num(c.capacity)}</td><td data-filter-value={c.free??''}>{c.free==null?'Belum diatur':num(c.free)}</td><td>{c.status}</td><td><Button variant="ghost" icon={Settings2} onClick={()=>editCapacity(c.code)}>Atur</Button></td></tr>})}</Table>}
 </Panel>}
 {fullMap&&<Modal fullscreen title="Peta rak 3D" onClose={()=>setFullMap(false)}><div className="rack-fullscreen-filters"><SearchBox value={query} onChange={setQuery} placeholder="Cari SKU atau lokasi…"/><Field label="Kelas ABC"><Select value={abc} onChange={e=>setAbc(e.target.value)}><option value="">Semua kelas</option>{['A','B','C'].map(c=><option key={c} value={c}>Kelas {c}</option>)}<option value="none">Belum diisi</option></Select></Field><Field label="Zona"><Select value={zone} onChange={e=>setZone(e.target.value)}><option value="">Semua zona</option>{[...new Set(locations.map(l=>l.zone))].sort().map(z=><option key={z} value={z}>{z}</option>)}</Select></Field><Field label="Isi peta"><Select value={mode} onChange={e=>setMode(e.target.value)}><option value="mapping">Mapping lokasi</option><option value="stock">Stok fisik</option></Select></Field>{(query||abc||zone)&&<Button variant="ghost" onClick={()=>{setQuery('');setAbc('');setZone('')}}>Hapus filter</Button>}</div><Rack3D s={s} query={query} abc={abc} zone={zone} mode={mode} onSelect={setSelected} expanded/></Modal>}
 {editing&&<LocationMappingEditor key={editing.item?.sku} s={s} act={act} accountId={accountId} item={editing.item} selectable={editing.selectable} onClose={()=>setEditing(null)}/>}
 {detail&&<Modal wide title={`Lokasi ${selected}`} subtitle={`${detail.status} · ${num(detail.used)} pcs tersimpan`} onClose={()=>setSelected('')}><div className="location-detail-head"><p>Kapasitas: {detail.capacity==null?'belum diatur':`${num(detail.capacity)} pcs`} · Sisa: {detail.free==null?'belum diketahui':`${num(detail.free)} pcs`}</p><Button icon={Settings2} variant="secondary" onClick={()=>editCapacity(selected)}>Atur kapasitas</Button></div><Table headers={['SKU / produk','ABC gudang','Mapping',{label:'Qty fisik (pcs)',type:'number'}]} empty={!locationAssignments(s,selected).length&&!s.stock.some(r=>r.locationCode===selected&&r.qty>0)}>{s.items.filter(i=>i.primaryLocation===selected||(i.reserveLocations||[]).includes(selected)||s.stock.some(r=>r.sku===i.sku&&r.locationCode===selected&&r.qty>0)).map(i=><tr key={i.sku}><td><Product item={i}/></td><td><AbcBadge value={i.abcClass}/></td><td>{i.primaryLocation===selected?'Utama':i.reserveLocations?.includes(selected)?'Reserve':'Di luar mapping'}</td><td>{num(s.stock.filter(r=>r.sku===i.sku&&r.locationCode===selected).reduce((n,r)=>n+r.qty,0))}</td></tr>)}</Table></Modal>}
 {capacity&&<Modal title={`Kapasitas ${capacity.locationCode}`} onClose={()=>setCapacity(null)}><form onSubmit={async e=>{e.preventDefault();const ok=await act(d=>saveLocationCapacity(d,capacity,accountId),'Kapasitas diperbarui. Rekomendasi Putaway mengikuti kondisi terbaru.');if(ok)setCapacity(null)}}><Field label="Kapasitas lokasi (pcs)" type="number" min="1" step="1" required value={capacity.capacity} onChange={e=>setCapacity({...capacity,capacity:e.target.value})}/><label className="location-block-toggle"><input type="checkbox" checked={capacity.putawayBlocked} onChange={e=>setCapacity({...capacity,putawayBlocked:e.target.checked})}/><span>Penuh sementara — hentikan putaway ke lokasi ini</span></label><Notice>Gunakan penanda penuh sementara jika ruang fisik sudah tidak cukup. Hilangkan penanda setelah lokasi bisa menerima barang kembali.</Notice><div className="modal-actions"><Button variant="secondary" type="button" onClick={()=>setCapacity(null)}>Batal</Button><Button type="submit">Simpan kapasitas</Button></div></form></Modal>}
 </>;
}
