import React,{useState,useEffect} from 'react';
import {Download,Users,Clock} from 'lucide-react';
import {Panel,Table,Field,Select,Button,Badge,num,Notice} from '../ui.jsx';
import {productivity,processes,activeWork} from '../lib/productivity.js';
import {csv,download} from '../lib/files.js';
export default function Productivity({s,cutoff}){
 const [mode,setMode]=useState('teams'),[team,setTeam]=useState('ALL'),[person,setPerson]=useState('ALL'),[process,setProcess]=useState('ALL'),[tick,setTick]=useState(Date.now());useEffect(()=>{const timer=setInterval(()=>setTick(Date.now()),10000);return()=>clearInterval(timer)},[]);
 const data=productivity(s,{start:cutoff,end:Date.now(),teamId:team,userId:person,process}),rows=data[mode],running=s.workSessions.filter(w=>w.status==='RUNNING'&&(team==='ALL'||w.teamId===team)&&(person==='ALL'||w.userId===person)&&(process==='ALL'||w.process===process));
 const exportRows=()=>download('produktivitas-gudang.csv',csv(rows.map(r=>({nama:r.name,tim:r.teamName,proses:processes[r.process],jamOperator:r.hours,lineUnik:r.lines,linePerJam:r.linesPerHour??'',qty:r.qty,satuan:r.unit,qtyPerJam:r.qtyPerHour??''}))));
 return <Panel title="Produktivitas operasional" subtitle="Line item dan qty per jam kerja aktif · mengikuti periode dashboard" action={<Button icon={Download} variant="ghost" onClick={exportRows}>Ekspor</Button>}>
 <div className="productivity-controls"><div className="tabs"><button className={mode==='teams'?'active':''} onClick={()=>setMode('teams')}>Per tim</button><button className={mode==='people'?'active':''} onClick={()=>setMode('people')}>Per orang</button></div><div className="productivity-filters"><Field label="Tim"><Select value={team} onChange={e=>{setTeam(e.target.value);setPerson('ALL')}}><option value="ALL">Seluruh tim</option>{s.teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</Select></Field><Field label="Operator"><Select value={person} onChange={e=>setPerson(e.target.value)}><option value="ALL">Semua operator</option>{s.workers.filter(w=>team==='ALL'||w.teamId===team).map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</Select></Field><Field label="Proses"><Select value={process} onChange={e=>setProcess(e.target.value)}><option value="ALL">Semua proses</option>{Object.entries(processes).map(([k,v])=><option key={k} value={k}>{v}</option>)}</Select></Field></div></div>
 <div className="productivity-live"><Clock size={16}/><strong>{running.length} operator sedang bekerja</strong><span>{running.map(w=>`${w.userName} · ${processes[w.process]}`).join(' / ')||'Belum ada sesi berjalan'}</span></div>
 <Table key={mode} resetKey={`${team}|${person}|${process}|${cutoff}`} headers={[mode==='teams'?'Tim':'Operator',...(mode==='people'?['Tim']:[]),'Proses',{label:'Jam operator',type:'number'},{label:'Line unik',type:'number'},{label:'Line / jam',type:'number'},{label:'Qty',type:'number'},'Satuan',{label:'Qty / jam',type:'number'}]} empty={!rows.length}>{rows.map(r=><tr key={r.id}><td className="strong">{r.name}</td>{mode==='people'&&<td>{r.teamName}</td>}<td>{processes[r.process]}</td><td data-filter-value={r.hours}>{num(r.hours)}</td><td>{r.lines}</td><td data-filter-value={r.linesPerHour}>{r.linesPerHour==null?'—':num(r.linesPerHour)}</td><td>{num(r.qty)}</td><td>{r.unit}</td><td data-filter-value={r.qtyPerHour} className="strong">{r.qtyPerHour==null?'—':num(r.qtyPerHour)}</td></tr>)}</Table>
 <details className="productivity-definition"><summary>Cara menghitung produktivitas</summary><p>Line unik adalah kombinasi dokumen, SKU, dan lokasi/referensi yang diproses pada periode terpilih. Scan berulang tidak menambah line. Pada penerimaan koli, line dihitung dari daftar SKU sesuai resi di koli yang tiba; qty menggunakan satuan koli. Proses lainnya menggunakan pcs.</p><p>Line/jam dan qty/jam = total hasil ÷ jam kerja aktif. Jeda tidak dihitung. Per tim menggunakan penjumlahan jam kerja seluruh operator dan line unik tim. Angka per jam ditampilkan setelah ada minimal 1 menit waktu aktif. Catatan lama tanpa sesi kerja tidak dihitung.</p><p>Selesaikan atau jeda sesi saat berhenti bekerja; penghitung tetap berjalan ketika berpindah halaman atau menutup aplikasi.</p></details>
 </Panel>;
}
