import React,{useEffect,useState} from 'react';
import {Upload,Download,Printer,Check,ArrowRight,Box,ScanLine,FileSpreadsheet} from 'lucide-react';
import {Button,PageHead,Panel,Table,Field,Select,Modal,Notice,Product,Badge,num,ScanInput,Empty,SearchBox} from '../ui.jsx';
import {receiptLines} from '../lib/actions.js';
import {packingColumns,validatePackingList,importPackingList,receiveKoli,confirmKoliIntake,beginKoliCart,checkKoliItem,finishKoliCheck} from '../lib/phase1.js';
import {checkingQueue,activeCheckingCart,openCheckingCart,closeCheckingCart,cartBalance} from '../lib/carts.js';
import {receivingQueues} from '../lib/receiving-queues.js';
import {activeWork} from '../lib/productivity.js';
import {findItem,norm} from '../lib/data.js';
import {printLabels,readUpload,download,csv} from '../lib/files.js';
import WorkControl from '../WorkControl.jsx';
import TestingPack from './TestingPack.jsx';
import {OperationalDetails} from '../OperationalUI.jsx';
const reasons={SHORT_SHIPMENT:'Barang kurang',OVER_SHIPMENT:'Barang lebih',WRONG_ITEM:'Barang tidak sesuai',DAMAGED_IN_TRANSIT:'Rusak dalam perjalanan',UNEXPECTED_ITEM:'Item di luar daftar koli'};
export default function Receiving({s,act,notify,user,navigate}){
 const queues=receivingQueues(s),work=activeWork(s,user);
 const [stage,setStage]=useState(work?.process==='CHECKING'&&queues.checking.some(k=>k.koliNo===work.reference)?'check':queues.intakes.length&&s.packingLists?.length?'intake':queues.checking.length||s.checkingCarts?.some(c=>c.status==='OPEN'&&(c.userId===user||!c.userId))?'check':'upload'),[selection,setSelected]=useState(work?.process==='RECEIVING'?work.reference:'');
 const selected=queues.intakes.some(r=>r.internalResiNo===selection)?selection:queues.intakes[0]?.internalResiNo||'';
 const r=queues.intakes.find(r=>r.internalResiNo===selected),ks=s.kolis.filter(k=>k.internalResiNo===selected),pending=queues.pendingKolis.filter(k=>k.internalResiNo===selected),arrived=ks.filter(k=>k.arrivedAt).length,ready=work?.process==='RECEIVING'&&work.reference===selected;
 const choose=id=>{setSelected(id);setStage('intake')};
 return <><PageHead title="Penerimaan vendor" description="Resi → terima seluruh koli → periksa SKU dan jumlah."><Button variant="secondary" onClick={()=>navigate('sync')}>Ambil resi Mini ERP</Button><Button variant="secondary" onClick={()=>navigate('reports')}>Buka laporan</Button></PageHead>{stage==='upload'&&<OperationalDetails title="Data & panduan testing"><TestingPack s={s} act={act}/></OperationalDetails>}<div className="phase-steps">{[['upload','1','Data resi vendor'],['intake','2','Penerimaan koli'],['check','3','Pengecekan isi koli']].map(([key,step,label])=><button key={key} className={stage===key?'active':''} onClick={()=>setStage(key)}><b>{step}</b>{label}</button>)}</div>
 {stage==='upload'?<PackingUpload s={s} act={act} notify={notify} user={user} onImported={choose}/>:stage==='check'?<Checking s={s} act={act} user={user} navigate={navigate}/>:<>
 {queues.intakes.length>0&&<Panel><div className="form-pad"><Field label="Nomor resi / kiriman"><Select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Pilih nomor resi</option>{queues.intakes.map(r=><option key={r.internalResiNo} value={r.internalResiNo}>{r.externalResiNo||r.internalResiNo} · {r.vendorName} · {r.expedition}</option>)}</Select></Field>{r&&<div className="receipt-summary"><span><b>{r.vendorName}</b> · {r.expedition}</span><span>{arrived} / {r.expectedKoli} koli diterima</span><Badge status={r.status}/></div>}</div></Panel>}
 {!r?<Empty title="Tidak ada koli untuk diterima" description="Riwayat penerimaan tersedia di menu Laporan." action={queues.checking.length?<Button onClick={()=>setStage('check')}>Buka pengecekan isi koli</Button>:<Button variant="secondary" onClick={()=>setStage('upload')}>Unggah daftar isi resi</Button>}/>:<Panel title="Cocokkan koli fisik" subtitle={`Resi ${r.externalResiNo} · Daftar koli sesuai daftar isi resi vendor`} action={<Button variant="ghost" icon={Printer} disabled={!pending.length} onClick={()=>printLabels(pending.map(k=>({code:k.koliNo,label:`${k.vendorKoliNo} · ${k.position} · ${r.externalResiNo||r.internalResiNo}`})))}>Cetak label koli</Button>}>
 <WorkControl s={s} act={act} user={user} process="RECEIVING" reference={selected}/>
 {pending.length?<><div className="scan-section">{ready?<ScanInput key={selected} label="Kode koli vendor" placeholder="Scan / input nomor koli" allowPhoto submitLabel="Terima koli" onScan={code=>act(d=>receiveKoli(d,selected,code,user),'Koli fisik tercatat; riwayat tersedia di Laporan')}/>:<Notice>Klik Mulai kerja, lalu scan setiap koli yang benar-benar tiba.</Notice>}</div>
 <Table mobileColumns={[0,2,3,5]} key={selected} headers={['Koli vendor','Label WMS','Urutan',{label:'Line SKU',type:'number'},{label:'Qty daftar isi resi',type:'number'},'Aksi']}>{pending.map(k=><tr key={k.koliNo}><td className="mono strong">{k.vendorKoliNo}</td><td className="mono">{k.koliNo}</td><td>{k.position}</td><td>{k.expectedItems.length}</td><td>{k.expectedItems.reduce((n,l)=>n+l.qtyExpected,0)}</td><td><Button variant="ghost" disabled={!ready} onClick={()=>act(d=>receiveKoli(d,selected,k.koliNo,user),'Koli fisik tercatat; riwayat tersedia di Laporan')}>Terima koli</Button></td></tr>)}</Table></>:<Notice tone="green">Seluruh koli fisik telah diterima. Konfirmasi jumlah untuk membuka pengecekan isi koli.</Notice>}
 <div className="panel-footer"><strong>{arrived} / {r.expectedKoli} koli diterima</strong><Button icon={Check} disabled={!ready||arrived!==r.expectedKoli||!ks.length} onClick={async()=>{const ok=await act(d=>confirmKoliIntake(d,selected,user),'Penerimaan selesai; lanjut pengecekan isi koli.');if(ok)setStage('check')}}>Konfirmasi penerimaan koli</Button></div></Panel>}</>}

 </>;
}
function PackingUpload({s,act,notify,user,onImported}){
 const [preview,setPreview]=useState(null),[busy,setBusy]=useState(false);
 function template(example){const date=new Date().toISOString().slice(0,10);const common={vendorName:'Vendor Contoh',shippingDate:date,externalResiNo:'RESI-CONTOH-001',expedition:'Ekspedisi Contoh',totalKoli:2};const rows=example?[{...common,vendorKoliNo:'KOLI-VENDOR-01',poNumber:'PO-CONTOH-01',sku:s.items[0]?.sku||'',qty:24},{...common,vendorKoliNo:'KOLI-VENDOR-01',poNumber:'PO-CONTOH-01',sku:s.items[1]?.sku||'',qty:12},{...common,vendorKoliNo:'KOLI-VENDOR-02',poNumber:'',sku:s.items[2]?.sku||'',qty:12}]:[];download(example?'contoh-resi-vendor.csv':'template-resi-vendor.csv',example?csv(rows.map(r=>({...r,'hpp/item':30000}))):packingColumns.join(',')+'\r\n')}
 async function fileChanged(file){if(!file)return;setBusy(true);setPreview(null);try{const input=await readUpload(file),result=validatePackingList(s,input);setPreview({name:file.name,input,...result})}catch(e){notify(e.message,'error')}finally{setBusy(false)}}
 return <><Panel title="Unggah daftar isi resi vendor" subtitle="Satu baris untuk satu SKU + referensi PO dalam satu koli."><div className="upload-layout"><div><div className="head-actions"><Button icon={Download} variant="secondary" onClick={()=>template(false)}>Template kosong</Button><Button variant="ghost" onClick={()=>template(true)}>Contoh 2 koli</Button></div><p className="muted">Kolom wajib: nomor resi, vendor, ekspedisi, total koli, nomor koli vendor, SKU dan qty. Nomor PO dan tanggal kirim opsional.</p><p className="muted">totalKoli harus sama dengan jumlah nomor koli unik pada daftar isi resi. Tanggal: YYYY-MM-DD. SKU harus tersedia di Master SKU.</p></div><label className="dropzone"><FileSpreadsheet size={30}/><strong>{busy?'Memeriksa file…':'Pilih Excel / CSV daftar isi resi'}</strong><span>.xlsx, .csv, .tsv · maksimal 12 MB</span><input aria-label="Unggah daftar isi resi vendor" type="file" accept=".xlsx,.csv,.tsv" disabled={busy} onChange={e=>{fileChanged(e.target.files[0]);e.target.value=''}}/></label></div></Panel>
 {preview&&<Panel title={`Pratinjau · ${preview.name}`} subtitle={`${preview.groups.length} daftar isi resi · ${preview.rows.length} baris · ${preview.errors.length} kesalahan`} action={<Button icon={Check} disabled={!preview.rows.length||!!preview.errors.length||busy} onClick={async()=>{setBusy(true);try{let ids;const ok=await act(d=>{ids=importPackingList(d,preview.input,preview.name,user)},'Data resi tersimpan; lanjut terima koli fisik');if(ok){setPreview(null);onImported(ids[0])}}finally{setBusy(false)}}}>Simpan daftar isi resi</Button>}>
 {!!preview.errors.length&&<Notice tone="red">{preview.errors[0]}{preview.errors.length>1&&` · ${preview.errors.length-1} kesalahan lainnya tercantum pada tabel.`}</Notice>}
 <Table pageSize={25} headers={['Data resi','Vendor','Koli vendor','SKU','PO / referensi',{label:'Qty',type:'number'},{label:'Total koli',type:'number'},'Validasi']} empty={!preview.rows.length}>{preview.rows.map((r,i)=><tr key={i}><td>{r.externalResiNo}</td><td>{r.vendorName}</td><td>{r.vendorKoliNo}</td><td className="mono">{r.sku}</td><td>{r.poNumber}</td><td>{r.qty}</td><td>{r.totalKoli}</td><td>{r.errors.length?<span className="error-text">{r.errors.join('; ')}</span>:<Badge status="APPROVED">Valid</Badge>}</td></tr>)}</Table></Panel>}
 </>;
}
export function Checking({s,act,user,navigate}){
 const queue=checkingQueue(s),work=activeWork(s,user);
 const [selected,setSelected]=useState(()=>work?.process==='CHECKING'&&queue.some(k=>k.koliNo===work.reference)?work.reference:''),[search,setSearch]=useState('');
 const k=queue.find(k=>k.koliNo===selected),receipts=new Map(s.receipts.map(r=>[r.internalResiNo,r]));
 const visible=queue.filter(k=>norm([k.koliNo,k.vendorKoliNo,receipts.get(k.internalResiNo)?.vendorName].join(' ')).includes(norm(search)));
 return <>
 <CheckingCartControl s={s} act={act} user={user}/>
 <div className="receiving-layout checking-layout"><OperationalDetails key={selected||'pilih'} title={k?`Ganti koli · ${k.vendorKoliNo||k.koliNo}`:'Pilih koli menunggu'} className={!k?'required-choice':''}><Panel title="Pilih nomor koli" subtitle={`${queue.filter(k=>k.status==='PENDING').length} menunggu · ${queue.filter(k=>k.status==='CHECKING').length} sedang diperiksa`}>
 <div className="koli-search"><SearchBox value={search} onChange={setSearch} placeholder="Cari nomor koli atau vendor…"/></div>
 <div className="list-scroll">{visible.map(k=>{const r=receipts.get(k.internalResiNo),owner=s.workSessions.find(w=>w.process==='CHECKING'&&w.reference===k.koliNo&&w.status!=='CLOSED');return <button disabled={Boolean(owner&&owner.userId!==user)} type="button" aria-pressed={selected===k.koliNo} key={k.koliNo} className={`document-card ${selected===k.koliNo?'selected':''}`} onClick={()=>setSelected(k.koliNo)}><div className="document-icon"><Box size={20}/></div><div><strong>{k.vendorKoliNo||k.koliNo}</strong><span className="mono">{k.koliNo}</span><span>{r?.vendorName}</span><Badge status={k.status}/>{owner&&<span>Operator: {owner.userName}</span>}</div></button>})}
 {!visible.length&&<Empty title={search?'Nomor koli tidak ditemukan':'Tidak ada koli menunggu pengecekan'} description={search?'Cari nomor vendor atau label WMS.':'Koli yang sudah diterima lengkap akan tampil di sini.'}/>}</div>
 </Panel></OperationalDetails>
 {k?<KoliCheck key={`${k.koliNo}|${user}`} s={s} k={k} receipt={receipts.get(k.internalResiNo)} act={act} user={user} onFinished={()=>setSelected('')}/>:<Panel><Empty title="Pilih koli yang menunggu" description="Setelah memilih koli, masukkan nomor kereta lalu scan SKU dan qty."/></Panel>}
 </div></>;
}
export function CheckingCartControl({s,act,user}){
 const [draft,setDraft]=useState(''),[busy,setBusy]=useState(false),cart=activeCheckingCart(s,user),balance=cart?cartBalance(s,cart.cartNo):null;
 const unclaimed=(s.checkingCarts||[]).filter(c=>c.status==='OPEN'&&!c.userId);
 async function open(value){setBusy(true);try{const ok=await act(d=>openCheckingCart(d,value,user),'Kereta aktif untuk pengecekan beberapa koli');if(ok)setDraft('');return ok}finally{setBusy(false)}}
 async function close(code){setBusy(true);try{await act(d=>closeCheckingCart(d,code,user),'Kereta di-close. Kereta berisi barang tampil di Putaway; Anda dapat menggunakan kereta baru')}finally{setBusy(false)}}
 return <Panel title="Kereta pengisian" subtitle="Input sekali, gunakan untuk beberapa koli. Close kereta saat akan mengganti kereta atau menyerahkannya ke Putaway."><div className="checking-cart">
 {cart?<div className="active-cart"><Box size={24}/><div><span>Kereta aktif · Open</span><strong>{cart.cartNo}</strong><small>{balance.koliCount} koli · {balance.skuCount} SKU baik · {num(balance.qty)} pcs</small></div><Button icon={Check} disabled={busy} onClick={()=>close(cart.cartNo)}>Close kereta</Button></div>:<form className="cart-form" onSubmit={e=>{e.preventDefault();open(draft)}}><Field label="Nomor kereta" value={draft} required maxLength={40} autoComplete="off" placeholder="Contoh KRT-001" onChange={e=>setDraft(e.target.value)}/><Button type="submit" disabled={busy||!draft.trim()}>Gunakan kereta</Button></form>}
 {!!unclaimed.length&&<><Notice>Kereta dari pengecekan sebelumnya tetap tersimpan. Lanjutkan pengisian atau close untuk menyerahkan ke Putaway.</Notice><Table headers={['Nomor kereta',{label:'Qty baik',type:'number'},'Status','Aksi']}>{unclaimed.map(c=><tr key={c.id}><td>{c.cartNo}</td><td>{cartBalance(s,c.cartNo).qty}</td><td>Open</td><td><Button variant="ghost" disabled={busy||!!cart} onClick={()=>open(c.cartNo)}>Lanjutkan pengisian</Button><Button variant="secondary" disabled={busy} onClick={()=>close(c.cartNo)}>Close kereta</Button></td></tr>)}</Table></>}
 </div></Panel>;
}
function KoliCheck({s,k,receipt,act,user,onFinished}){
 const [po,setPo]=useState(''),[amount,setAmount]=useState(1),[condition,setCondition]=useState('GOOD'),[modal,setModal]=useState(false),[reason,setReason]=useState({});
 const [busy,setBusy]=useState(false),[pending,setPending]=useState(0),[lastScan,setLastScan]=useState(null);
 const cart=activeCheckingCart(s,user),cartNo=cart?.cartNo||'',cartMatches=!!cart;
 const lines=receiptLines(k),work=activeWork(s,user),ready=work?.process==='CHECKING'&&work.reference===k.koliNo;
 useEffect(()=>{if(ready&&cartMatches)document.getElementById('checking-sku')?.focus()},[ready,cartNo]);
 async function scan(code){setPending(n=>n+1);try{const next=await act(d=>checkKoliItem(d,k.koliNo,code,po,amount,condition,user,cartNo),`SKU dan qty tercatat ke kereta ${cartNo}`);if(next)setLastScan({sku:norm(code),qty:amount});return next}finally{setPending(n=>n-1)}}
 return <Panel title={`Cek isi · ${k.vendorKoliNo||k.koliNo}`} subtitle={`${k.koliNo} · ${receipt?.vendorName||''} · ${receipt?.externalResiNo||k.internalResiNo}`}>
 <WorkControl s={s} act={act} user={user} process="CHECKING" reference={k.koliNo} disabled={!cartMatches&&!k.scannedItems.length}/>
 <div className="scan-section">{ready&&cartMatches?<><div className="scan-options"><OperationalDetails title="Referensi PO"><Field label="PO / referensi"><Select value={po} onChange={e=>setPo(e.target.value)}><option value="">Otomatis sesuai SKU</option>{[...new Set(k.expectedItems.map(l=>l.poNumber))].map(po=><option key={po}>{po}</option>)}</Select></Field></OperationalDetails><Field label="Qty per scan" type="number" min="1" step="1" value={amount} onChange={e=>setAmount(e.target.value)}/><Field label="Kondisi"><Select value={condition} onChange={e=>setCondition(e.target.value)}><option value="GOOD">Baik</option><option value="DAMAGED">Rusak</option><option value="REJECT">Reject</option></Select></Field></div><ScanInput id="checking-sku" key={`${k.koliNo}|${cartNo}`} label="SKU pengecekan koli" placeholder={`Scan / input SKU ke ${cartNo}`} allowPhoto submitLabel="Simpan scan" onScan={scan}/></>:<Notice>{!cartMatches?'Masukkan dan konfirmasi nomor kereta untuk mulai scan SKU.':'Lanjutkan kerja untuk mencatat hasil pengecekan ke kereta.'}</Notice>}</div>
 {lastScan&&<div className="operation-last-scan" role="status">Tercatat: <strong>{lastScan.sku}</strong> · {num(lastScan.qty)} pcs · {cartNo}</div>}
 <OperationalDetails title={`Daftar SKU koli · ${lines.length} item`}><Table mobileColumns={[0,2,3,7]} headers={['SKU / produk','PO / referensi',{label:'Qty sesuai resi',type:'number'},{label:'Fisik',type:'number'},{label:'Selisih',type:'number'},{label:'Rusak / reject',type:'number'},'Kereta','Status']} empty={!lines.length}>{lines.map(l=><tr key={`${l.sku}|${l.poNumber}`}><td><Product sku={l.sku} item={findItem(s,l.sku)}/></td><td>{l.poNumber}</td><td>{l.expected}</td><td>{l.received}</td><td className={l.variance?'error-text':''}>{l.variance}</td><td>{l.bad}</td><td>{[...new Set(k.scannedItems.filter(row=>row.sku===l.sku&&row.poNumber===l.poNumber).map(row=>row.cartNo||'Belum dicatat'))].join(', ')||'—'}</td><td><Badge status={l.discrepancy?'DISCREPANCY':'APPROVED'}>{l.discrepancy?'Perlu diperiksa':'Sesuai'}</Badge></td></tr>)}</Table></OperationalDetails>
 <div className="panel-footer"><span>{num(lines.reduce((n,l)=>n+l.received,0))} / {num(lines.reduce((n,l)=>n+l.expected,0))} pcs</span><Button icon={Check} disabled={!ready||pending>0||busy||!lines.length} onClick={()=>{setReason({});setModal(true)}}>Selesaikan cek koli</Button></div>
 {!!k.scannedItems.length&&<OperationalDetails title="Rincian hasil scan per kereta"><div className="cart-scan-results"><div className="panel-head"><div><h2>Hasil scan per kereta</h2><p>Isi dari koli {k.vendorKoliNo||k.koliNo}. Nomor kereta tetap aktif lintas koli sampai di-close.</p></div></div><Table mobileColumns={[1,0,3,4]} headers={['Nomor kereta','SKU / produk','PO / referensi',{label:'Qty',type:'number'},'Kondisi']}>
 {k.scannedItems.map((row,i)=><tr key={i}><td className="mono strong">{row.cartNo||'Belum dicatat'}</td><td><Product sku={row.sku} item={findItem(s,row.sku)}/></td><td>{row.poNumber}</td><td>{row.qtyScanned}</td><td><Badge status={row.condition}/></td></tr>)}</Table></div></OperationalDetails>}
 {modal&&<Modal wide title="Selesaikan pengecekan isi koli" onClose={()=>setModal(false)}><p>Barang sesuai masuk staging. Selisih wajib memiliki alasan dan melalui persetujuan. Kereta tetap terbuka untuk koli berikutnya. Close kereta bila siap diserahkan ke Putaway.</p>{lines.filter(l=>l.discrepancy).map(l=><div className="discrepancy-row" key={`${l.sku}|${l.poNumber}`}><div><strong>{l.sku} · {l.poNumber}</strong><span>{l.received} / {l.expected} pcs · rusak/reject {l.bad}</span></div><Select aria-label={`Alasan ${l.sku} ${l.poNumber}`} value={reason[`${l.sku}|${l.poNumber}`]||''} onChange={e=>setReason({...reason,[`${l.sku}|${l.poNumber}`]:e.target.value})}><option value="">Pilih alasan</option>{Object.entries(reasons).map(([key,label])=><option key={key} value={key}>{label}</option>)}</Select></div>)}<div className="modal-actions"><Button variant="secondary" disabled={busy} onClick={()=>setModal(false)}>Kembali</Button><Button disabled={busy||pending>0} onClick={async()=>{setBusy(true);try{const ok=await act(d=>finishKoliCheck(d,k.koliNo,reason,user),'Pengecekan koli selesai. Kereta tetap aktif untuk koli berikutnya; Close kereta saat siap Putaway');if(ok){setModal(false);onFinished()}}finally{setBusy(false)}}}>Konfirmasi selesai</Button></div></Modal>}
 </Panel>;
}
