import React,{useState} from 'react';
import {Plus,Pencil,Save} from 'lucide-react';
import {PageHead,Panel,Table,Button,Modal,Field,Select,Badge,Notice} from '../ui.jsx';
import {menuCatalog,effectiveMenus,saveAppUser,saveRole,saveSystemSettings} from '../lib/access.js';
import {reportTime} from '../lib/reports.js';

const localNotice=<Notice tone="blue">Pengaturan user dan akses berlaku pada mode uji lokal. Pemilihan User uji belum menggunakan autentikasi login server.</Notice>;
export function UserManagement({s,act,accountId}){
 const [f,setF]=useState(null),[busy,setBusy]=useState(false),set=(key,value)=>setF(f=>({...f,[key]:value}));
 const role=s.roles.find(r=>r.id===f?.roleId),preview=f?{...s,appUsers:[...s.appUsers.filter(u=>u.id!==f.id),{...f,id:'PREVIEW',active:true}]}:s;
 return <><PageHead title="User Management" eyebrow="PENGATURAN" description="Kelola user, operator terkait, role, dan akses menu khusus."><Button icon={Plus} onClick={()=>setF({name:'',username:'',email:'',roleId:'INBOUND',workerId:s.workers.find(w=>w.active)?.id||'',active:true,menuOverrides:{}})}>Tambah user</Button></PageHead>{localNotice}
 <Panel><Table headers={['Nama','Username','Email','Role','Operator','Status',{label:'Menu aktif',type:'number'},'Aksi']} empty={!s.appUsers.length}>{s.appUsers.map(u=><tr key={u.id}><td>{u.name}</td><td>{u.username}</td><td>{u.email||'—'}</td><td>{s.roles.find(r=>r.id===u.roleId)?.name}</td><td>{s.workers.find(w=>w.id===u.workerId)?.name||'—'}</td><td><Badge status={u.active?'APPROVED':'CANCELLED'}>{u.active?'Aktif':'Nonaktif'}</Badge></td><td>{effectiveMenus(s,u.id).length}</td><td><Button icon={Pencil} variant="ghost" onClick={()=>setF({...u,menuOverrides:{...u.menuOverrides}})}>Edit</Button></td></tr>)}</Table></Panel>
 {f&&<Modal wide title={f.id?'Ubah user':'Tambah user'} onClose={()=>setF(null)}><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{const ok=await act(d=>saveAppUser(d,f,accountId),'User dan akses menu tersimpan');if(ok)setF(null)}finally{setBusy(false)}}}>
 <div className="form-grid"><Field label="Nama user" required value={f.name} onChange={e=>set('name',e.target.value)}/><Field label="Username" required value={f.username} onChange={e=>set('username',e.target.value)}/><Field label="Email (opsional)" type="email" value={f.email} onChange={e=>set('email',e.target.value)}/><Field label="Operator produktivitas"><Select value={f.workerId} onChange={e=>set('workerId',e.target.value)}>{s.workers.filter(w=>w.active||w.id===f.workerId).map(w=><option key={w.id} value={w.id}>{w.name}{!w.active?' (nonaktif)':''}</option>)}</Select></Field><Field label="Role"><Select value={f.roleId} onChange={e=>set('roleId',e.target.value)}>{s.roles.filter(r=>r.active||r.id===f.roleId).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</Select></Field><label className="check-label"><input type="checkbox" checked={f.active} onChange={e=>set('active',e.target.checked)}/>User aktif</label></div>
 <h3>Akses menu tiap user</h3><p className="muted settings-help">Ikuti role untuk akses standar, atau izinkan/blokir menu khusus user ini.</p>
 <Table headers={['Menu','Akses role','Pengaturan user','Akses efektif']} pageSize={25}>{menuCatalog.map(([id,label])=>{const value=f.menuOverrides[id]===true?'allow':f.menuOverrides[id]===false?'deny':'inherit';return <tr key={id}><td>{label}</td><td>{role?.menus.includes(id)?'Diizinkan':'Diblokir'}</td><td data-filter-value={value}><Select aria-label={`Akses ${label}`} disabled={f.roleId==='ADMIN'} value={value} onChange={e=>{const next={...f.menuOverrides};if(e.target.value==='inherit')delete next[id];else next[id]=e.target.value==='allow';set('menuOverrides',next)}}><option value="inherit">Ikuti role</option><option value="allow">Izinkan</option><option value="deny">Blokir</option></Select></td><td>{effectiveMenus(preview,'PREVIEW').includes(id)?'Diizinkan':'Diblokir'}</td></tr>})}</Table>
 <div className="modal-actions"><Button type="button" variant="secondary" onClick={()=>setF(null)}>Batal</Button><Button icon={Save} disabled={busy} type="submit">Simpan user</Button></div></form></Modal>}</>;
}

export function RoleManagement({s,act,accountId}){
 const [f,setF]=useState(null),[busy,setBusy]=useState(false),set=(key,value)=>setF(f=>({...f,[key]:value}));
 return <><PageHead title="Role Management" eyebrow="PENGATURAN" description="Tentukan akses menu standar dan jenjang persetujuan tiap role."><Button icon={Plus} onClick={()=>setF({name:'',active:true,menus:[],approvalRole:'OPERATOR'})}>Tambah role</Button></PageHead>
 <Panel><Table headers={['Role','Peran persetujuan',{label:'Jumlah menu',type:'number'},{label:'User',type:'number'},'Status','Aksi']}>{s.roles.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.approvalRole}</td><td>{r.menus.length}</td><td>{s.appUsers.filter(u=>u.roleId===r.id).length}</td><td><Badge status={r.active?'APPROVED':'CANCELLED'}>{r.active?'Aktif':'Nonaktif'}</Badge></td><td><Button variant="ghost" icon={Pencil} onClick={()=>setF({...r,menus:[...r.menus]})}>Edit</Button></td></tr>)}</Table></Panel>
 {f&&<Modal wide title={f.id?'Ubah role':'Tambah role'} onClose={()=>setF(null)}><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{const ok=await act(d=>saveRole(d,f,accountId),'Role dan akses menu tersimpan');if(ok)setF(null)}finally{setBusy(false)}}}><div className="form-grid"><Field label="Nama role" required value={f.name} onChange={e=>set('name',e.target.value)}/><Field label="Peran persetujuan"><Select value={f.approvalRole} onChange={e=>set('approvalRole',e.target.value)}>{['OPERATOR','PPIC','SPV','MANAGER'].map(value=><option key={value}>{value}</option>)}</Select></Field></div><label className="check-label"><input type="checkbox" checked={f.active} disabled={f.id==='ADMIN'} onChange={e=>set('active',e.target.checked)}/>Role aktif</label>
 {f.id==='ADMIN'?<Notice>Administrator selalu memiliki seluruh akses pengaturan agar aplikasi tetap dapat dikelola.</Notice>:<div className="settings-menu-actions"><Button type="button" variant="ghost" onClick={()=>set('menus',menuCatalog.map(([id])=>id))}>Pilih semua menu</Button><Button type="button" variant="ghost" onClick={()=>set('menus',[])}>Kosongkan pilihan</Button></div>}
 <Table headers={['Menu','Diizinkan']} pageSize={25}>{menuCatalog.map(([id,label])=><tr key={id}><td>{label}</td><td data-filter-value={f.menus.includes(id)?'Ya':'Tidak'}><input type="checkbox" aria-label={`Izinkan ${label}`} checked={f.menus.includes(id)} disabled={f.id==='ADMIN'} onChange={e=>set('menus',e.target.checked?[...f.menus,id]:f.menus.filter(key=>key!==id))}/></td></tr>)}</Table><div className="modal-actions"><Button type="button" variant="secondary" onClick={()=>setF(null)}>Batal</Button><Button icon={Save} disabled={busy} type="submit">Simpan role</Button></div></form></Modal>}</>;
}

export function SystemSettings({s,act,accountId}){
 const [f,setF]=useState({...s.systemSettings}),[busy,setBusy]=useState(false),set=(key,value)=>setF(f=>({...f,[key]:value}));
 return <><PageHead title="Pengaturan Sistem" eyebrow="PENGATURAN" description="Identitas gudang dan tampilan aplikasi."/>{localNotice}<Panel><form className="form-pad" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await act(d=>saveSystemSettings(d,f,accountId),'Pengaturan sistem tersimpan')}finally{setBusy(false)}}}><div className="form-grid"><Field label="Nama perusahaan" required value={f.companyName} onChange={e=>set('companyName',e.target.value)}/><Field label="Nama gudang" required value={f.warehouseName} onChange={e=>set('warehouseName',e.target.value)}/><Field label="Halaman awal"><Select value={f.landingPage} onChange={e=>set('landingPage',e.target.value)}>{menuCatalog.map(([id,label])=><option key={id} value={id}>{label}</option>)}</Select></Field><Field label="Baris tabel per halaman"><Select value={f.tablePageSize} onChange={e=>set('tablePageSize',e.target.value)}>{[10,15,25,50].map(n=><option key={n} value={n}>{n} baris</option>)}</Select></Field></div><div className="form-footer"><Button icon={Save} type="submit" disabled={busy}>Simpan pengaturan</Button></div></form></Panel>
 <Panel title="Riwayat perubahan pengaturan"><Table headers={['Waktu (WITA)','User','Perubahan','Referensi']} empty={!s.settingsAudit.length}>{s.settingsAudit.slice().reverse().map(row=><tr key={row.id}><td>{reportTime(row.at)}</td><td>{row.actor}</td><td>{row.action}</td><td>{row.reference}</td></tr>)}</Table></Panel></>;
}
