import React,{useRef,useState} from 'react';
import {Download,Printer,BookOpen} from 'lucide-react';
import {Panel,Button,Modal,Table,Notice,Product,num,Field,Select} from '../ui.jsx';
import {download,csv,printLabels} from '../lib/files.js';
import {findItem} from '../lib/data.js';
import {generateTestingResi} from '../lib/testing-data.js';
const scenarios={cycle:'Siklus normal',mixed:'SKU sama di beberapa koli',reserve:'Reserve & pembagian qty'};
export default function TestingPack({s,act}){
 const [open,setOpen]=useState(false),[scenario,setScenario]=useState('cycle'),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),lock=useRef(false);
 if(!s.testing)return null;
 const packs=s.testing.resiDownloads||[],pack=packs.find(p=>p.id===selected)||packs.at(-1),rows=pack?.rows||s.testing.packingRows,planned=s.testing.planned,total=rows.reduce((n,r)=>n+r.qty,0),koliCount=new Set(rows.map(r=>r.vendorKoliNo)).size,imported=s.receipts.some(r=>r.externalResiNo===rows[0].externalResiNo&&r.expedition===rows[0].expedition);
 async function generate(kind){
  if(lock.current)return;lock.current=true;setBusy(true);setError('');
  try{let generated;const next=await act(d=>{generated=generateTestingResi(d,kind)});if(next&&generated){setSelected(generated.id);download(generated.filename,csv(generated.rows))}}
  catch(e){setError(e.message||'Unduhan belum berhasil. Coba lagi.')}finally{lock.current=false;setBusy(false)}
 }
 const codes=kind=>kind==='koli'?[...new Set(rows.map(r=>r.vendorKoliNo))].map(code=>{const contents=rows.filter(r=>r.vendorKoliNo===code);return {code,label:`Koli vendor uji · ${contents.length} line · ${contents.reduce((n,r)=>n+r.qty,0)} pcs`}}):kind==='kereta'?(s.cartMasters||[]).map(c=>({code:c.cartNo,label:`Kereta uji · kapasitas ${c.capacity} pcs`})):kind==='sku'?[...new Set(rows.map(r=>r.sku))].map(sku=>({code:sku,label:findItem(s,sku)?.itemName||sku})):planned.flatMap(p=>[{code:p.locationCode,label:`Utama · ${p.sku}`},...(p.reserveLocations||[]).map(code=>({code,label:`Reserve · ${p.sku}`}))]);
 return <><Panel className="testing-pack" title="Paket uji Receiving siap" subtitle={`${rows.length} line · ${koliCount} koli · ${num(total)} pcs · ${s.items.length} SKU · ${s.stores.length} cabang`} action={<Button variant="ghost" icon={BookOpen} onClick={()=>setOpen(true)}>Panduan & label uji</Button>}>
 <div className="testing-pack-body"><p>Setiap unduhan membuat file baru dengan resi, nomor koli, susunan item dan qty berbeda. Unggah file tersebut pada langkah 1: Data resi vendor.</p><Field label="Skenario testing"><Select disabled={busy} value={scenario} onChange={e=>setScenario(e.target.value)}>{Object.entries(scenarios).map(([id,label])=><option key={id} value={id}>{label}</option>)}</Select></Field><Button variant="secondary" disabled={busy} icon={Download} onClick={()=>generate(scenario)}>{busy?'Menyiapkan resi…':`Unduh data resi uji · ${scenario==='reserve'?4:20} line`}</Button><small>Stok dan transaksi dibersihkan satu kali untuk siklus uji baru. Unduhan dan refresh berikutnya tidak mereset pekerjaan Anda.</small></div>
 {error&&<Notice tone="red">{error}</Notice>}
 {scenario==='reserve'&&<Notice>Uji ini mencakup qty yang perlu dibagi ke reserve dan sisa yang tertahan di kereta. Jalankan setelah lokasi utama terisi; ikuti rekomendasi Putaway dan tambah kapasitas/mapping bila diperlukan.</Notice>}
 <div className="testing-reserve-actions"><p>Mapping lokasi utama, reserve dan kapasitas tersedia di Location control.</p><Button variant="secondary" disabled={busy} icon={Download} onClick={()=>generate('reserve')}>Unduh resi uji reserve · 4 line</Button></div>
 {pack&&<div className="testing-pack-body"><Field label="Panduan untuk file yang sudah dibuat"><Select value={pack.id} onChange={e=>setSelected(e.target.value)}>{packs.map(p=><option key={p.id} value={p.id}>#{p.sequence} · {scenarios[p.scenario]} · {p.rows[0].externalResiNo}</option>)}</Select></Field><p>{imported?'Resi ini sudah diunggah. Lanjutkan proses di antrian Receiving.':'Resi ini belum diunggah.'} {num(total)} pcs · {koliCount} koli. Panduan dan label mengikuti file yang dipilih.</p></div>}
 </Panel>
 {open&&<Modal wide title="Panduan testing dari Receiving" subtitle={pack?`${scenarios[pack.scenario]} · ${rows[0].externalResiNo}`:'Unduh resi terlebih dahulu agar panduan mengikuti file Anda.'} onClose={()=>setOpen(false)}>
 <Notice tone="blue">Unduhan tidak menambah stok. Upload resi hanya membuat daftar penerimaan; stok masuk staging setelah pengecekan selesai. Kerjakan siklus normal dahulu, lalu gunakan skenario tambahan.</Notice>
 <p className="testing-master-summary">Master siap: {s.items.length} SKU, {s.locations.length} lokasi, {s.stores.length} cabang, {Object.keys(s.demand).length} pasangan DAD dan klasifikasi, {Object.keys(s.safety).length} parameter safety stock, {s.cartMasters.length} kereta, {s.teams.length} tim, {s.appUsers.length} user, {s.roles.length} role.</p>
 <ol className="guide-list"><li><strong>Upload & penerimaan koli</strong><p>Pilih Administrator Uji atau Operator Inbound 01. Unduh dan unggah resi, periksa pratinjau, lalu Simpan data resi. Mulai kerja, terima setiap nomor koli pada file, kemudian Konfirmasi penerimaan koli.</p></li><li><strong>Pengecekan isi</strong><p>Pilih koli menunggu, gunakan KRT-UJI-001 atau kereta uji lain, lalu scan SKU dan qty sesuai file. Satu kereta dapat memuat beberapa koli. Selesaikan pengecekan tiap koli, lalu Close kereta untuk diserahkan ke Putaway.</p></li><li><strong>Putaway</strong><p>Pilih kereta Close, scan SKU, periksa qty, kemudian scan lokasi utama/reserve yang direkomendasikan. Jika ruang tidak cukup, bagi qty ke lokasi terdaftar. Kereta kosong bisa digunakan kembali.</p></li><li><strong>Alokasi & picking</strong><p>Gunakan Administrator Uji atau PPIC Uji untuk simulasi dan konfirmasi alokasi ke 12 store. Operator Outbound 01 scan KRT-OUT-001 (60 pcs) atau KRT-OUT-002 (120 pcs), lalu ambil batch. Ikuti lokasi, qty dan SKU pada tugas. Kapasitas kereta dapat membagi satu store menjadi beberapa batch.</p></li><li><strong>Packing & shipping</strong><p>Operator Outbound 02 memilih store, membuka nomor koli packing, lalu memasukkan hasil picking finish dari kereta. Satu koli boleh berisi beberapa batch untuk store yang sama. Seal koli dan konfirmasi shipping. Stok DC berkurang, barang dalam perjalanan ke store bertambah; hasilnya ada di Laporan dan dashboard.</p></li><li><strong>Skenario lanjutan</strong><p>SKU sama di beberapa koli menguji penggabungan hasil pengecekan. Reserve & pembagian qty menguji lokasi penuh dan sisa kereta. Untuk uji selisih, masukkan qty fisik berbeda, isi alasan, lalu tuntaskan persetujuan Supervisor Uji dan Manager Uji sebelum Putaway.</p></li></ol>
 <div className="head-actions testing-label-actions">{[['koli','Label koli'],['kereta','Label kereta'],['sku','Label SKU'],['lokasi','Label lokasi']].map(([key,label])=><Button key={key} variant="secondary" icon={Printer} onClick={()=>printLabels(codes(key))}>{label}</Button>)}</div>
 <Table pageSize={25} headers={['Koli vendor','PO / referensi','SKU / produk',{label:'Qty fisik',type:'number'},'Kereta','ABC gudang','Lokasi utama','Lokasi reserve']}>
 {rows.map((r,i)=>{const item=findItem(s,r.sku);return <tr key={`${r.vendorKoliNo}-${r.sku}-${i}`}><td className="mono">{r.vendorKoliNo}</td><td>{r.poNumber}</td><td><Product item={item}/></td><td>{r.qty}</td><td className="mono">KRT-UJI-001</td><td>{item?.abcClass||'—'}</td><td className="mono">{item?.primaryLocation||'—'}</td><td>{(item?.reserveLocations||[]).join(', ')||'—'}</td></tr>})}</Table>
 <p className="muted">Nomor resi: {rows[0].externalResiNo}. Setiap file cukup diunggah satu kali. Nomor kereta muncul di Putaway setelah berisi hasil pengecekan dan di-close.</p>
 </Modal>}</>;
}
