import React,{useRef,useState} from 'react';
import RackStructureEditor from './RackStructureEditor.jsx';
import {ArrowDown,ArrowLeft,ArrowRight,ArrowUp,RotateCw,Save,Plus} from 'lucide-react';
import {Button,Field,Select,Notice,Table,num,Modal} from '../ui.jsx';
import {currentWarehouseLayout,storageRacks,layoutIssues,moveRack,rackFootprint,rackPoint,saveWarehouseLayout,addLayoutLocations} from '../lib/warehouse-layout.js';

export function LayoutFloorPlan({layout,selected,onSelect,onMove,busy=false,issues=[]}){
 const svg=useRef(),drag=useRef();
 const width=Number(layout.warehouse.width),depth=Number(layout.warehouse.depth);
 if(!(width>0&&depth>0&&Number.isFinite(width+depth)))return <Notice>Isi ukuran gudang untuk menampilkan denah.</Notice>;
 const invalid=new Set(issues.flatMap(e=>e.racks));
 const point=e=>{const p=svg.current.createSVGPoint();p.x=e.clientX;p.y=e.clientY;return p.matrixTransform(svg.current.getScreenCTM().inverse())};
 const stop=()=>{drag.current=null};
 const marker=Math.max(width,depth)*0.005;
 function start(e,r){if(busy||e.button!==0)return;e.preventDefault();onSelect(r.id);const p=point(e);drag.current={id:r.id,x:Number(r.x),y:Number(r.y),px:p.x,py:p.y,pointer:e.pointerId};svg.current.setPointerCapture(e.pointerId)}
 const ticks=Array.from({length:Math.min(20,Math.ceil(Math.max(width,depth)))+1},(_,i)=>i*Math.max(1,Math.ceil(Math.max(width,depth)/20)));
 return <div className="layout-floor-wrap"><div className="layout-floor-caption"><strong>Tampak atas · {num(width)} × {num(depth)} m</strong><span>Titik 0,0 di sudut kiri atas</span></div>
 <svg ref={svg} className="layout-floor" viewBox={`-${marker*6} -${marker*6} ${width+marker*12} ${depth+marker*12}`} role="group" aria-label="Editor tata letak rak tampak atas" onPointerMove={e=>{if(!drag.current||busy)return;const p=point(e),d=drag.current;onMove(d.id,d.x+p.x-d.px,d.y+p.y-d.py)}} onPointerUp={stop} onPointerCancel={stop} onLostPointerCapture={stop}>
 <rect x="0" y="0" width={width} height={depth} fill="#f2f6fa" stroke="#7392ad" strokeWidth={marker}/>
 {ticks.filter(n=>n>0&&n<width).map(n=><line key={`x${n}`} x1={n} y1={0} x2={n} y2={depth} stroke="#dce6ee" strokeWidth={marker/3}/>)}
 {ticks.filter(n=>n>0&&n<depth).map(n=><line key={`y${n}`} x1={0} y1={n} x2={width} y2={n} stroke="#dce6ee" strokeWidth={marker/3}/>)}
 {layout.racks.map(r=>{
  const f=rackFootprint(r);if(!Number.isFinite(f.x+f.y+f.width+f.depth)||f.width<=0||f.depth<=0)return null;
  const textSize=Math.min(f.width/Math.max(4,r.id.length),f.depth*0.3),front=rackPoint(r,[Number(r.width)/2,Number(r.depth)*0.85]);
  return <g key={r.id} role="button" tabIndex={busy?-1:0} aria-label={`Atur rak ${r.id}, X ${r.x} meter, Y ${r.y} meter, arah ${r.rotation} derajat`} aria-pressed={selected===r.id} className={`layout-rack ${selected===r.id?'selected':''}`} onClick={()=>onSelect(r.id)} onPointerDown={e=>start(e,r)} onKeyDown={e=>{
   if(busy)return;
   const step=e.shiftKey?1:0.1,directions={ArrowLeft:[-step,0],ArrowRight:[step,0],ArrowUp:[0,-step],ArrowDown:[0,step]};
   if(directions[e.key]){e.preventDefault();onSelect(r.id);onMove(r.id,Number(r.x)+directions[e.key][0],Number(r.y)+directions[e.key][1])}
   else if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(r.id)}
  }}>
  <rect x={f.x} y={f.y} width={f.width} height={f.depth} rx={marker} fill={invalid.has(r.id)?'#f9dddd':selected===r.id?'#285a81':'#d7e5ef'} stroke={invalid.has(r.id)?'#b33938':selected===r.id?'#193d59':'#789aB5'} strokeWidth={marker*(selected===r.id?1.6:0.7)}/>
  <text x={f.x+f.width/2} y={f.y+f.depth/2+textSize*0.32} textAnchor="middle" fontFamily="Arial,sans-serif" fontWeight="700" fontSize={textSize} fill={selected===r.id&&!invalid.has(r.id)?'white':'#234963'}>{r.id}</text>
  <circle cx={front[0]} cy={front[1]} r={Math.min(f.width,f.depth)*0.05} fill={selected===r.id?'#ffd276':'#8e6423'}/>
  </g>;
 })}</svg><p>Geser rak atau gunakan input posisi. Titik kuning menandai sisi depan. Panah keyboard: 0,1 m; Shift + panah: 1 m.</p></div>;
}

export default function WarehouseLayoutEditor({s,act,accountId,onView3D}){
 const [draft,setDraft]=useState(()=>currentWarehouseLayout(s)),[base,setBase]=useState(()=>currentWarehouseLayout(s)),[selected,setSelected]=useState(()=>storageRacks(s)[0]?.id||''),[busy,setBusy]=useState(false),[adding,setAdding]=useState(null),[editingStructure,setEditingStructure]=useState('');
 const catalog=storageRacks(s),r=draft.racks.find(r=>r.id===selected),issues=layoutIssues(draft,catalog.map(r=>r.id)),dirty=JSON.stringify(draft)!==JSON.stringify(base),stale=(s.warehouseLayout?.revision||0)!==base.revision;
 function change(key,value){setDraft(d=>({...d,racks:d.racks.map(r=>r.id===selected?{...r,[key]:value}:r)}))}
 function move(id,x,y){setDraft(d=>moveRack(d,id,x,y))}
 function load(){const latest=currentWarehouseLayout(s);setDraft(latest);setBase(latest);setSelected(id=>latest.racks.some(r=>r.id===id)?id:latest.racks[0]?.id||'')}
 async function save(e){e.preventDefault();if(busy||issues.length)return;setBusy(true);try{const next=await act(d=>saveWarehouseLayout(d,{...draft,expectedRevision:base.revision},accountId),'Tata letak tersimpan. Rak 3D dan monitoring luas lantai diperbarui.');if(next){const saved=currentWarehouseLayout(next);setDraft(saved);setBase(saved)}}finally{setBusy(false)}}
 return <div className="warehouse-layout-editor"><div className="layout-editor-intro"><div><h2>Atur tata letak rak aktual</h2><p>Isi hasil pengukuran dalam meter, pilih rak, lalu geser atau tentukan koordinatnya.</p></div><div className="head-actions"><Button icon={Plus} disabled={busy} onClick={()=>setAdding({rack:selected,firstLevel:1,lastLevel:1,firstBin:1,lastBin:1,capacity:''})}>Tambah lokasi</Button><Button variant="secondary" onClick={onView3D}>Lihat rak 3D tersimpan</Button></div></div>
 {!base.configured&&<Notice>Layout awal adalah contoh otomatis. Sesuaikan ukuran gudang, ukuran rak, dan posisi aktual lalu simpan.</Notice>}
 {!!base.unplaced.length&&base.configured&&<Notice>{base.unplaced.length} rak baru belum ditempatkan. Sesuaikan posisinya lalu simpan seluruh layout.</Notice>}
 {stale&&<Notice tone="red">Layout telah diperbarui. Muat layout terbaru sebelum melanjutkan.</Notice>}
 <form onSubmit={save}><div className="layout-floor-settings"><Field label="Lebar gudang / sumbu X (m)" type="number" min="0.1" max="10000" step="0.01" required disabled={busy} value={draft.warehouse.width} onChange={e=>setDraft({...draft,warehouse:{...draft.warehouse,width:e.target.value}})}/><Field label="Panjang gudang / sumbu Y (m)" type="number" min="0.1" max="10000" step="0.01" required disabled={busy} value={draft.warehouse.depth} onChange={e=>setDraft({...draft,warehouse:{...draft.warehouse,depth:e.target.value}})}/><div className="layout-area-preview"><span>Luas lantai pada denah</span><strong>{num(Number(draft.warehouse.width)*Number(draft.warehouse.depth)||0)} m²</strong><small>{draft.racks.length} rak dari Master lokasi</small></div></div>
 <div className="layout-editor-grid"><LayoutFloorPlan layout={draft} selected={selected} onSelect={setSelected} onMove={move} busy={busy} issues={issues}/><aside className="layout-rack-form"><Field label="Rak yang diatur"><Select value={selected} disabled={busy} onChange={e=>setSelected(e.target.value)}>{draft.racks.map(r=><option key={r.id} value={r.id}>Rak {r.id}</option>)}</Select></Field>
 {r?<><div className="layout-input-grid">{[['x','Posisi X (m)',0],['y','Posisi Y (m)',0],['width','Lebar rak (m)',0.1],['depth','Dalam rak (m)',0.1],['height','Tinggi rak (m)',0.1]].map(([key,label,min])=><Field key={key} label={label} type="number" min={min} max="10000" step="0.01" required disabled={busy} value={r[key]} onChange={e=>change(key,e.target.value)}/>)}<Field label="Arah rak"><Select value={r.rotation} disabled={busy} onChange={e=>change('rotation',Number(e.target.value))}>{[0,90,180,270].map(v=><option key={v} value={v}>{v}°</option>)}</Select></Field></div>
 <div className="layout-structure-control"><div><strong>{catalog.find(c=>c.id===r.id)?.levels.length||0} level · {catalog.find(c=>c.id===r.id)?.bins.length||0} bin</strong><span>{catalog.find(c=>c.id===r.id)?.cells.length||0} lokasi pada rak</span></div><Button type="button" variant="secondary" disabled={busy} onClick={()=>setEditingStructure(r.id)}>Ubah bin & level</Button></div>
 <div className="layout-nudge" role="group" aria-label="Geser rak terpilih"><Button type="button" variant="secondary" icon={ArrowLeft} disabled={busy} aria-label="Geser rak kiri 10 cm" onClick={()=>move(r.id,Number(r.x)-0.1,Number(r.y))}/><Button type="button" variant="secondary" icon={ArrowUp} disabled={busy} aria-label="Geser rak atas 10 cm" onClick={()=>move(r.id,Number(r.x),Number(r.y)-0.1)}/><Button type="button" variant="secondary" icon={ArrowDown} disabled={busy} aria-label="Geser rak bawah 10 cm" onClick={()=>move(r.id,Number(r.x),Number(r.y)+0.1)}/><Button type="button" variant="secondary" icon={ArrowRight} disabled={busy} aria-label="Geser rak kanan 10 cm" onClick={()=>move(r.id,Number(r.x)+0.1,Number(r.y))}/><Button type="button" variant="secondary" icon={RotateCw} disabled={busy} onClick={()=>change('rotation',(Number(r.rotation)+90)%360)}>Putar</Button></div><small>X/Y menunjuk sudut kiri atas tapak rak setelah diputar. Ukuran lebar/dalam mengikuti badan rak.</small></>:<p>Klik Tambah lokasi untuk membuat lokasi dan rak baru.</p>}</aside></div>
 {issues.length>0&&<div className="layout-errors" role="alert"><strong>{issues.length} pengaturan perlu diperbaiki</strong><ul>{issues.slice(0,6).map((e,i)=><li key={i}>{e.message}</li>)}</ul>{issues.length>6&&<p>Dan {issues.length-6} pengaturan lainnya.</p>}</div>}
 <div className="layout-save-bar"><span role="status">{dirty?'Perubahan belum disimpan':base.configured?'Layout tersimpan':'Contoh layout · belum disimpan'}</span><Button type="button" variant="secondary" disabled={busy} onClick={load}>{stale?'Muat layout terbaru':'Batalkan perubahan'}</Button><Button type="submit" icon={Save} disabled={busy||stale||!!issues.length}>{busy?'Menyimpan…':'Simpan tata letak'}</Button></div></form>
 <details className="layout-coordinates"><summary>Daftar posisi dan ukuran rak</summary><Table mobileColumns={[0,1,2,6,8]} headers={['Rak',{label:'X (m)',type:'number'},{label:'Y (m)',type:'number'},{label:'Lebar (m)',type:'number'},{label:'Dalam (m)',type:'number'},{label:'Tinggi (m)',type:'number'},'Arah',{label:'Lokasi',type:'number'},'Aksi']} empty={!draft.racks.length}>{draft.racks.map(r=><tr key={r.id}><td className="mono strong">{r.id}</td>{['x','y','width','depth','height'].map(k=><td key={k} data-filter-value={r[k]}>{num(r[k])}</td>)}<td>{r.rotation}°</td><td>{catalog.find(c=>c.id===r.id)?.cells.length||0}</td><td><Button variant="ghost" onClick={()=>setSelected(r.id)}>Atur rak</Button></td></tr>)}</Table></details>
 {editingStructure&&<RackStructureEditor s={s} rack={editingStructure} act={act} accountId={accountId} onClose={()=>setEditingStructure('')}/>}
 {adding&&<Modal title="Tambah lokasi gudang" subtitle="Lokasi langsung terdaftar di Master lokasi dan dapat dipetakan ke SKU." onClose={()=>setAdding(null)}><form onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);try{const next=await act(d=>addLayoutLocations(d,adding,accountId),'Lokasi ditambahkan. Sesuaikan ukuran dan posisi rak lalu simpan tata letak.');if(next){const current=currentWarehouseLayout(next);setDraft(d=>({...d,racks:[...d.racks,...current.racks.filter(r=>!d.racks.some(old=>old.id===r.id)).map(r=>({...r,x:0,y:0}))]}));setSelected(adding.rack.trim().toUpperCase());setAdding(null)}}finally{setBusy(false)}}}><Field label="Nomor rak" placeholder="A03" required maxLength={3} value={adding.rack} onChange={e=>setAdding({...adding,rack:e.target.value.toUpperCase()})}/><div className="form-grid">{[['firstLevel','Level dari',9],['lastLevel','Level sampai',9],['firstBin','Bin dari',99],['lastBin','Bin sampai',99]].map(([key,label,max])=><Field key={key} label={label} type="number" min="1" max={max} step="1" required value={adding[key]} onChange={e=>setAdding({...adding,[key]:e.target.value})}/>)}</div><Field label="Kapasitas setiap lokasi (pcs)" type="number" min="1" step="1" required value={adding.capacity} onChange={e=>setAdding({...adding,capacity:e.target.value})}/><Notice>Contoh: rak A03, level 1–3, bin 1–4 menghasilkan 12 lokasi. Kode yang sudah terdaftar akan ditolak.</Notice><div className="modal-actions"><Button type="button" variant="secondary" onClick={()=>setAdding(null)}>Batal</Button><Button type="submit" disabled={busy}>Tambahkan lokasi</Button></div></form></Modal>}
 </div>;
}
