import React from 'react';
import assert from 'node:assert/strict';
import {renderToStaticMarkup as render} from 'react-dom/server';
import {seed} from '../src/lib/data.js';
import {createTestingState} from '../src/lib/testing-data.js';
import {defaultWarehouseLayout,saveWarehouseLayout,currentWarehouseLayout} from '../src/lib/warehouse-layout.js';
import LocationControl from '../src/modules/LocationControl.jsx';
import Dashboard from '../src/modules/Dashboard.jsx';
import Rack3D,{rackScene,rackGeometry} from '../src/modules/Rack3D.jsx';
import WarehouseUtilization from '../src/modules/WarehouseUtilization.jsx';
import {LayoutFloorPlan} from '../src/modules/WarehouseLayoutEditor.jsx';
const s=createTestingState(seed()),props={s,act:()=>{},accountId:'USER-ADMIN',navigate:()=>{}};
let html=render(<LocationControl {...props} initial="layout"/>);
for(const text of ['Space utilization gudang','Utilisasi lokasi','Utilisasi kapasitas','Luas lantai untuk rak','Atur tata letak rak aktual','Simpan tata letak','Posisi X (m)','Geser rak kiri 10 cm','Atur rak A01'])assert(html.includes(text),text);
for(const c of ['Rak','X (m)','Y (m)','Lebar (m)','Dalam (m)','Tinggi (m)','Arah','Lokasi','Aksi'])assert(html.includes(`aria-label="Filter ${c}"`),c);
assert(html.includes('Layout awal adalah contoh otomatis'));assert(html.includes('Ukuran aktual belum lengkap'));
const initial=defaultWarehouseLayout(s);initial.warehouse={width:30,depth:20};Object.assign(initial.racks[0],{x:20,y:14,rotation:90});
saveWarehouseLayout(s,{...initial,expectedRevision:0},'USER-ADMIN');
s.stock.push({sku:s.items[0].sku,locationCode:s.items[0].primaryLocation,qty:20});
const summary=render(<WarehouseUtilization s={s}/>),dashboard=render(<Dashboard {...props}/>),control=render(<LocationControl {...props}/>);
assert(dashboard.includes('Monitoring utilisasi gudang'));assert(control.includes(summary.slice(summary.indexOf('<div class="space-metrics"'),summary.lastIndexOf('</section>'))));
assert(dashboard.includes(summary.slice(summary.indexOf('<div class="space-metrics"'),summary.lastIndexOf('</section>'))));
const geometry=rackGeometry(s,rackScene(s,{abc:'A'}));assert.equal(geometry.find(r=>r.id==='A01').x,20);assert.equal(geometry.find(r=>r.id==='A01').rotation,90);
assert.equal(rackGeometry(s,rackScene(s,{query:s.items[0].sku}))[0].levels.length,3);
html=render(<Rack3D s={s}/>);assert(html.includes('data-rack="A01" data-x="20" data-y="14" data-rotation="90"'));assert(!html.includes('NaN'));assert(!html.includes('Infinity'));
const plan=render(<LayoutFloorPlan layout={currentWarehouseLayout(s)} selected="A01" onSelect={()=>{}} onMove={()=>{}}/>);assert(plan.includes('aria-pressed="true"'));assert(plan.includes('arah 90 derajat'));
console.log('Layout editor, all coordinate filters, rotated 3D geometry and identical Dashboard/Location control utilization passed.');
