import React from 'react';
import assert from 'node:assert/strict';
import {renderToStaticMarkup as render} from 'react-dom/server';
import {seed,newId} from '../src/lib/data.js';
import {createTestingState} from '../src/lib/testing-data.js';
import {createCapacityBatches,scanPickingCart,claimPickBatch,pickCartBatchItem,openPackingKoli,packCartIntoKoli,sealPackingKoli} from '../src/lib/outbound.js';
import {Picking,Packing} from '../src/modules/CartFulfillment.jsx';
import {Shipping} from '../src/modules/Fulfillment.jsx';
import WarehouseLayoutEditor from '../src/modules/WarehouseLayoutEditor.jsx';
import {LocationMappingEditor} from '../src/modules/LocationMapping.jsx';
import {rackScene} from '../src/modules/Rack3D.jsx';
const s=createTestingState(seed()),user='OP-OUT-01',props={s,user,act:()=>{},navigate:()=>{},accountId:'USER-ADMIN'};
let html=render(<Picking {...props}/>);assert(html.includes('Kereta picking'));assert(!html.includes('Filter Batch'));assert(!html.includes('SKU ke kereta picking'));
html=render(<WarehouseLayoutEditor {...props}/>);assert(html.includes('Tambah lokasi'));
html=render(<LocationMappingEditor {...props} item={s.items[0]} onClose={()=>{}}/>);assert(html.includes('ABC dari Master SKU'));assert(!html.includes('Klasifikasi ABC gudang'));
html=render(<LocationMappingEditor {...props} menu="master" item={s.items[0]} onClose={()=>{}}/>);assert(html.includes('Klasifikasi ABC gudang'));
const sku=s.items[0].sku,location=s.items[0].primaryLocation;s.items[0].abcClass='C';const scene=rackScene(s,{query:sku});assert(scene.some(r=>r.classes.includes('C')));s.items[0].abcClass='B';assert(rackScene(s,{query:sku}).some(r=>r.classes.includes('B')));
s.stock=[{sku,locationCode:location,qty:80}];s.allocations=[{allocationNo:'AL-RENDER',status:'CONFIRMED',lines:[{sku,storeId:'ST01',allocatedQty:80}]}];s.picks=[{id:'P-RENDER',storeId:'ST01',allocationNo:'AL-RENDER',status:'READY',lines:[{sku,qty:80,pickedQty:0,packedQty:0,sources:[]}]}];
const ids=createCapacityBatches(s,{pickIds:['P-RENDER'],capacity:40,startLocation:location},user);scanPickingCart(s,'KRT-RENDER',user,80);
html=render(<Picking {...props}/>);for(const c of ['Batch','Store','Qty (pcs)','Line lokasi','Operator','Aksi'])assert(html.includes(`aria-label="Filter ${c}"`));assert(html.includes('Ambil batch'));
claimPickBatch(s,ids[0],user);html=render(<Picking {...props}/>);assert(html.includes('Lokasi pengambilan'));assert(html.includes('SKU ke kereta picking'));assert(html.includes('max="40"'));assert(html.includes('Masukkan ke kereta'));
const batch=s.pickBatches[0];for(const task of batch.tasks)pickCartBatchItem(s,batch.id,task.id,{sku:task.sku,location:task.location,qty:task.qty,cartNo:batch.cartNo,requestId:newId()},user);
html=render(<Packing {...props} user="OP-OUT-02"/>);assert(html.includes('Nomor koli outbound'));assert(html.includes('Buat nomor koli otomatis'));
openPackingKoli(s,'KO-RENDER','ST01','OP-OUT-02');html=render(<Packing {...props} user="OP-OUT-02"/>);assert(html.includes('Kereta asal packing'));assert(html.includes('KO-RENDER'));
packCartIntoKoli(s,{koliNo:'KO-RENDER',cartNo:'KRT-RENDER',sku,qty:15,requestId:newId()},'OP-OUT-02');sealPackingKoli(s,'KO-RENDER','OP-OUT-02');html=render(<Shipping {...props}/>);assert(html.includes('Filter Nomor koli'));assert(html.includes('Filter Batch asal'));assert(html.includes('KO-RENDER'));
console.log('Outbound render OK: scan-cart gate, locked batch, task controls, packing koli, shipping trace, layout addition and Master SKU ABC.');
