import React from 'react';
import assert from 'node:assert/strict';
import {renderToStaticMarkup} from 'react-dom/server';
import {seed} from '../src/lib/data.js';
import {createTestingState} from '../src/lib/testing-data.js';
import Rack3D,{rackScene} from '../src/modules/Rack3D.jsx';
import {Table} from '../src/FilterTable.jsx';
const s=createTestingState(seed()),before=structuredClone(s),first=s.items[0];
const scene=rackScene(s);
assert.equal(scene.length,s.locations.filter(l=>l.allocatable).length);
assert(scene.find(l=>l.code===first.primaryLocation).classes.includes(first.abcClass));
assert(rackScene(s,{abc:'B'}).every(l=>l.classes.includes('B')));
assert(rackScene(s,{zone:'B'}).every(l=>l.zone==='B'));
assert(rackScene(s,{query:first.sku}).every(l=>l.entries.some(r=>r.item.sku===first.sku)));
assert(rackScene(s,{mode:'stock'}).every(l=>!l.entries.length));
const html=renderToStaticMarkup(<Rack3D s={s} onSelect={()=>{}}/>);
for(const label of ['Layout rak 3D','Putar rak ke kiri','Perbesar','Lihat dari atas',`Lokasi ${first.primaryLocation}`])assert(html.includes(label),label);
assert.equal((html.match(/class="rack3d-bin"/g)||[]).length,scene.length);
assert.equal((html.match(/class="rack3d-bin" role="button" tabindex="0"/g)||[]).length,scene.length);
const emptyHtml=renderToStaticMarkup(<Rack3D s={s} mode="stock"/>);
assert(!emptyHtml.includes('class="rack3d-bale"'),'Zero-stock locations must have empty shelves');
assert.equal((emptyHtml.match(/class="rack3d-bin" role="button" tabindex="0"/g)||[]).length,scene.length);
assert(html.includes('/assets/rack-textile-higgsfield.webp'));
assert(html.includes('Isi bal merupakan ilustrasi'));
assert.deepEqual(s,before);
s.stock.push({sku:first.sku,locationCode:first.reserveLocations[0],qty:12});
s.items[0].abcClass='C';
const actual=rackScene(s,{mode:'stock',query:first.sku});
assert.equal(actual.length,1);assert.equal(actual[0].used,12);assert.deepEqual(actual[0].classes,['C']);
const compact=renderToStaticMarkup(<Table headers={['SKU','Qty','Lokasi','Aksi']} mobileColumns={[0,1,3]}><tr><td>SKU-1</td><td>5</td><td>A01-1-01</td><td><button>Pilih</button></td></tr></Table>);
assert(compact.includes('operation-card'));assert(compact.includes('Filter Lokasi'));assert(compact.includes('Filter Aksi'));
console.log('3D rack mapping, stock, filters, interactive targets and compact table filters OK.');
