import {seed} from './mapped-fixture.mjs';
import {receiveKoli,confirmKoliIntake} from '../src/lib/phase1.js';
import {startWork} from '../src/lib/productivity.js';
function receiveAll(s,id){const user=s.workers[0].id;startWork(s,'RECEIVING',id,user);for(const k of s.kolis.filter(k=>k.internalResiNo===id&&!k.arrivedAt))receiveKoli(s,id,k.koliNo,user);confirmKoliIntake(s,id,user)}
import test from 'node:test';import assert from 'node:assert/strict';
import {available,physical,reserved,applyMutation,latestState,pickedAt,qty,move,newId} from '../src/lib/data.js';
import {createReceipt,scanItem,closeKoli,putaway,saveAllocation,approve,pickItem,shortPick,packItem,seal,ship} from '../src/lib/actions.js';
import {calculateSOQ,validateAllocation} from '../web/js/lib/allocation.js';
const sku='B01-106A2';
function rows(s,n=10){const key=`ST01_${sku}`,st=s.stores[0],c=s.classification[key].class,ss=s.safety[`ST01_${c}`];const line=calculateSOQ({sku,storeId:'ST01',dad:s.demand[key].dad,itemClass:c,oc:st.orderCycleDays,lt:st.leadTimeDays,ssd:ss.ssDemandDays,sslt:ss.ssLeadTimeDays,oh:s.oh[key],od:s.od[key]});return [{sku,available:available(s,sku),totalSOQ:line.soq,lines:[{...line,allocatedQty:n,isManualOverride:false,overrideReason:''}]}]}
const balance=s=>({general:physical(s,sku),staging:s.stock.filter(r=>r.sku===sku&&r.locationCode[0]==='S').reduce((n,r)=>n+r.qty,0),reserved:reserved(s,sku),available:available(s,sku),od:s.od[`ST01_${sku}`]});
test('Full receiving → putaway → allocation → SPV → Manager → pick → pack → ship cycle stays consistent',()=>{let s=seed();const snapshots=[];const transact=fn=>{s=applyMutation(s,fn)};const capture=stage=>snapshots.push({stage,...balance(s)});capture('Initial');transact(d=>receiveAll(d,d.receipts[0].internalResiNo));const k=s.kolis[0].koliNo;for(const item of s.kolis[0].expectedItems)transact(d=>scanItem(d,k,item.sku,item.poNumber,item.qtyExpected,'GOOD'));transact(d=>closeKoli(d,k,{},'QA'));assert.equal(s.receipts[0].status,'CLOSED');capture('Receiving');transact(d=>putaway(d,{sku,from:'S01-1-01',to:'A01-1-01',qty:24},'QA'));capture('Putaway');const r=rows(s);r[0].lines[0].isManualOverride=true;r[0].lines[0].overrideReason='Uji distribusi 10 pcs';transact(d=>saveAllocation(d,r,'FAIR_SHARE_COVERAGE',true,'QA','2026-09-06'));capture('Reserved');assert.equal(s.picks.length,0);const a=s.approvals[0].id;transact(d=>approve(d,a,'SPV',true,'Cocok','QA'));assert.equal(s.picks.length,0);transact(d=>approve(d,a,'MANAGER',true,'Disetujui','QA'));assert.equal(s.allocations[0].status,'CONFIRMED');const p=s.picks[0].id;transact(d=>pickItem(d,p,{sku,location:'A01-1-01',qty:10},'QA'));capture('Picking');assert.equal(s.queue.filter(q=>q.target==='MOKA').length,1);transact(d=>packItem(d,p,sku,10));transact(d=>seal(d,p));assert.equal(s.orders[0].lines[0].qty,10);const order=s.orders[0].doNumber;transact(d=>ship(d,order,'QA'));capture('Shipping');assert.deepEqual(snapshots,[{stage:'Initial',general:100,staging:24,reserved:0,available:100,od:12},{stage:'Receiving',general:100,staging:48,reserved:0,available:100,od:12},{stage:'Putaway',general:124,staging:24,reserved:0,available:124,od:12},{stage:'Reserved',general:124,staging:24,reserved:10,available:114,od:12},{stage:'Picking',general:124,staging:24,reserved:10,available:114,od:12},{stage:'Shipping',general:114,staging:24,reserved:0,available:114,od:22}]);assert.equal(s.orders[0].status,'SHIPPED');assert.equal(s.picks[0].status,'SHIPPED');assert.equal(s.allocations[0].lines[0].shippedQty,10);assert.equal(s.allocations[0].paramSnapshot[0].od,12);assert.equal(rows(s)[0].lines[0].soq,50);assert.equal(s.queue.filter(q=>q.event==='TRANSFER_STOCK').length,1);assert.equal(s.queue.filter(q=>q.target==='MINI_ERP'&&q.event==='RECEIVING').length,3);assert.equal(new Set(s.movements.map(m=>m.movementId)).size,s.movements.length);assert(s.movements.every(m=>Number.isSafeInteger(m.qty)));const persisted=structuredClone(s);assert.deepEqual(balance(persisted),balance(s));console.log('Cycle balances:',JSON.stringify(snapshots))});
test('Receipt parent follows every koli; reasons synchronize into scanned records',()=>{let s=seed();let id;s=applyMutation(s,d=>{id=createReceipt(d,{externalResiNo:'QA-2',expedition:'QA',count:2},'QA')});const ks=s.kolis.filter(k=>k.internalResiNo===id);s=applyMutation(s,d=>{for(const k of d.kolis.filter(k=>k.internalResiNo===id))k.expectedItems=[{sku,poNumber:'QA-PO',qtyExpected:2}];receiveAll(d,id);scanItem(d,ks[0].koliNo,sku,'QA-PO',2,'GOOD');closeKoli(d,ks[0].koliNo,{},'QA')});assert.equal(s.receipts.find(r=>r.internalResiNo===id).status,'CHECKING');s=applyMutation(s,d=>{scanItem(d,ks[1].koliNo,sku,'QA-PO',1,'GOOD');closeKoli(d,ks[1].koliNo,{[`${sku}|QA-PO`]:'SHORT_SHIPMENT'},'QA')});assert.equal(s.receipts.find(r=>r.internalResiNo===id).status,'DISCREPANCY');assert.equal(s.kolis.find(k=>k.koliNo===ks[1].koliNo).scannedItems[0].discrepancyReason,'SHORT_SHIPMENT');const a=s.approvals.at(-1).id;s=applyMutation(s,d=>approve(d,a,'SPV',true,'Kurang','QA'));s=applyMutation(s,d=>approve(d,a,'MANAGER',true,'Terima fisik','QA'));assert.equal(s.receipts.find(r=>r.internalResiNo===id).status,'CLOSED')});
test('Late refresh cannot replace a newer module state',()=>{const s=seed(),a=applyMutation(s,d=>putaway(d,{sku,from:'S01-1-01',to:'A01-1-01',qty:1},'A')),b=applyMutation(a,d=>putaway(d,{sku,from:'S01-1-01',to:'A01-1-01',qty:1},'B'));assert.equal(latestState(b,a),b);assert.equal(latestState(a,b),b);assert.equal(physical(s,sku),100);assert.equal(physical(b,sku),102);assert.equal(b.revision,2)});
test('Failed multi-line mutation rolls back all changes and audit entries',()=>{const s=seed(),before=structuredClone(s);assert.throws(()=>applyMutation(s,d=>{putaway(d,{sku,from:'S01-1-01',to:'A01-1-01',qty:1},'QA');putaway(d,{sku,from:'S01-1-01',to:'A01-1-01',qty:99999},'QA')}));assert.deepEqual(s,before);assert.throws(()=>applyMutation(s,()=>Promise.resolve()),/atomik/)});
test('Stale DAD, classification, parameters, OH or OD invalidates confirmation even if DC stock is unchanged',()=>{for(const mutate of [d=>d.demand[`ST01_${sku}`].dad++,d=>d.classification[`ST01_${sku}`].class='B',d=>d.stores[0].leadTimeDays++,d=>d.safety.ST01_A.ssDemandDays++,d=>d.oh[`ST01_${sku}`]++,d=>d.od[`ST01_${sku}`]++]){let s=seed();const r=rows(s),oldAvailable=available(s,sku);s=applyMutation(s,mutate);assert.equal(available(s,sku),oldAvailable);assert.throws(()=>applyMutation(s,d=>saveAllocation(d,r,'FAIR_SHARE_COVERAGE',true,'QA','2026-09-06')),/parameter atau stok cabang berubah/);assert.equal(s.allocations.length,0)}});
test('Saving a stale draft retains its original availability snapshot',()=>{let s=seed();const r=rows(s);s=applyMutation(s,d=>putaway(d,{sku,from:'S01-1-01',to:'A01-1-01',qty:1},'QA'));s=applyMutation(s,d=>saveAllocation(d,r,'FAIR_SHARE_COVERAGE',false,'QA','2026-09-06'));assert.equal(s.allocations[0].availableSnapshot[sku],100);assert.equal(available(s,sku),101)});
test('Putaway cannot relabel general stock as a new inbound addition',()=>{const s=seed();assert.throws(()=>applyMutation(s,d=>putaway(d,{sku,from:'A01-1-01',to:'B01-1-01',qty:1},'QA')),/staging/)});
test('Partial short-pick omits zero-quantity lines from DO and Moka queue',()=>{let s=seed();const r=rows(s);const item2=s.items[1].sku,k=`ST01_${item2}`;const l=calculateSOQ({sku:item2,storeId:'ST01',dad:s.demand[k].dad,itemClass:'B',oc:7,lt:3,ssd:1,sslt:2,oh:s.oh[k],od:s.od[k]});r.push({sku:item2,available:available(s,item2),totalSOQ:l.soq,lines:[{...l,allocatedQty:2,isManualOverride:false,overrideReason:''}]});s=applyMutation(s,d=>saveAllocation(d,r,'FAIR_SHARE_COVERAGE',true,'QA','2026-09-06'));const p=s.picks[0].id;s=applyMutation(s,d=>pickItem(d,p,{sku,location:'A01-1-01',qty:10},'QA'));s=applyMutation(s,d=>shortPick(d,p,item2,'Tidak ditemukan','QA'));s=applyMutation(s,d=>{packItem(d,p,sku,10);seal(d,p)});assert.equal(s.orders[0].lines.length,1);s=applyMutation(s,d=>ship(d,d.orders[0].doNumber,'QA'));assert.equal(s.queue.filter(q=>q.event==='TRANSFER_STOCK').length,1);assert(s.queue.filter(q=>q.event==='TRANSFER_STOCK').every(q=>q.payload.qty>0))});
test('Opname cannot reduce source stock while picked units remain in the ledger',()=>{let s=seed();s=applyMutation(s,d=>saveAllocation(d,rows(d),'FAIR_SHARE_COVERAGE',true,'QA','2026-09-06'));s=applyMutation(s,d=>pickItem(d,d.picks[0].id,{sku,location:'A01-1-01',qty:10},'QA'));assert.equal(pickedAt(s,sku,'A01-1-01'),10);s.counts.push({id:'SO-QA',sku,locationCode:'A01-1-01',systemQty:100,physicalQty:90,variance:-10});s.approvals.push({id:'AP-QA',type:'OPNAME',refDoc:'SO-QA',status:'PENDING_MANAGER',history:[]});const before=structuredClone(s);assert.throws(()=>applyMutation(s,d=>approve(d,'AP-QA','MANAGER',true,'Cek','QA')),/picking/);assert.deepEqual(s,before)});
test('Opname in staging never queues sellable Moka stock adjustment',()=>{let s=seed();s.counts.push({id:'SO-QA',sku,locationCode:'S01-1-01',systemQty:24,physicalQty:25,variance:1});s.approvals.push({id:'AP-QA',type:'OPNAME',refDoc:'SO-QA',status:'PENDING_MANAGER',history:[]});s=applyMutation(s,d=>approve(d,'AP-QA','MANAGER',true,'Cocok','QA'));assert.equal(balance(s).staging,25);assert.equal(s.queue.length,0);assert.equal(available(s,sku),100)});
test('Malformed quantity and duplicate allocation rows are rejected',()=>{for(const value of ['',null,undefined,Number.MAX_SAFE_INTEGER+1])assert.throws(()=>qty(value));const s=seed(),l=rows(s)[0].lines[0];assert.throws(()=>validateAllocation([l,l],{[sku]:100}),/duplikat/);assert.match(newId(),/^[0-9a-f-]{36}$/)});
