import React,{useEffect,useRef,useState} from 'react';
import {X,Search,ArrowUpRight,PackageOpen,Camera,LoaderCircle,ChevronLeft,ChevronRight,ScanLine,AlertCircle} from 'lucide-react';
import {readBarcodePhoto} from './lib/barcode.js';
export const num=v=>new Intl.NumberFormat('id-ID',{maximumFractionDigits:2}).format(v??0);
export const time=v=>v?new Date(v).toLocaleString('id-ID',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}):'—';
export const sizeLabel=v=>({0:'XS',1:'S',2:'M',3:'L',4:'XL',5:'2XL',6:'3XL',7:'4XL',8:'S–M',9:'L–XL'}[v]||v);
const labels={AWAITING_KOLI:'Menunggu koli',RECEIVING_KOLI:'Penerimaan koli',READY_TO_CHECK:'Siap cek isi',ARRIVED:'Koli diterima',PICKING_FINISH:'Picking finish',FINISHED:'Selesai',SHORT:'Short-pick',PENDING:'Menunggu',CHECKING:'Diperiksa',CLOSED:'Selesai',DISCREPANCY:'Ada selisih',READY:'Siap diproses',DRAFT:'Draft',CONFIRMED:'Dikonfirmasi',PENDING_SPV:'Menunggu SPV',PENDING_MANAGER:'Menunggu Manager',APPROVED:'Disetujui',REJECTED:'Ditolak',CANCELLED:'Dibatalkan',PICKING:'Dalam picking',PICKED:'Siap packing',PACKED:'Siap kirim',SHIPPED:'Terkirim',PRIORITY:'Prioritas hitung',WAITING_CONFIGURATION:'Belum terhubung',SELLABLE:'Layak jual',NON_SELLABLE:'Non-sellable',SYNCED:'Tersinkron',FAILED:'Gagal',GOOD:'Baik',DAMAGED:'Rusak',REJECT:'Reject'};
export function Badge({status,children}){const tone=['CLOSED','CONFIRMED','APPROVED','SHIPPED','SELLABLE','SYNCED','ARRIVED','PICKING_FINISH','FINISHED'].includes(status)?'green':['DISCREPANCY','REJECTED','FAILED','CANCELLED'].includes(status)?'red':['PENDING_SPV','PENDING_MANAGER','PRIORITY','PENDING','CHECKING','PICKING','WAITING_CONFIGURATION'].includes(status)?'amber':'blue';return <span className={`badge ${tone}`}>{children||labels[status]||status}</span>}
export function Button({children,icon:Icon,variant='primary',className='',...props}){return <button className={`btn ${variant} ${className}`} {...props}>{Icon&&<Icon size={17}/>}<span>{children}</span></button>}
export function PageHead({eyebrow,title,description,children}){return <div className="page-head"><div><div className="eyebrow">{eyebrow||'OPERASIONAL GUDANG'}</div><h1>{title}</h1>{description&&<p>{description}</p>}</div><div className="head-actions">{children}</div></div>}
export function Panel({title,subtitle,action,children,className=''}){return <section className={`panel ${className}`}>{title&&<div className="panel-head"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>}{children}</section>}
export function Empty({title='Belum ada data',description,action}){return <div className="empty"><PackageOpen size={32}/><h3>{title}</h3>{description&&<p>{description}</p>}{action}</div>}
export function SearchBox({value,onChange,placeholder='Cari data…'}){return <div className="searchbox"><Search size={18}/><input aria-label={placeholder} value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/>{value&&<button aria-label="Hapus pencarian" onClick={()=>onChange('')}><X size={16}/></button>}</div>}
export function Field({label,children,hint,...props}){return <label className="field"><span>{label}</span>{children||<input {...props}/>} {hint&&<small>{hint}</small>}</label>}
export function Select({children,...props}){return <select {...props}>{children}</select>}
export function Notice({children,tone='amber'}){return <div className={`notice ${tone}`}><AlertCircle size={18}/><div>{children}</div></div>}
export function Modal({title,subtitle,children,onClose,wide=false,fullscreen=false}){const ref=useRef(),previous=useRef();useEffect(()=>{previous.current=document.activeElement;ref.current?.focus();const handler=e=>{if([...document.querySelectorAll('.modal[role="dialog"]')].at(-1)!==ref.current)return;if(e.key==='Escape')onClose();if(e.key==='Tab'){const els=[...ref.current.querySelectorAll('button,input,select,textarea,[tabindex="0"]')].filter(el=>!el.disabled);const first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',handler);return()=>{document.removeEventListener('keydown',handler);previous.current?.focus()}},[]);return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className={`modal ${wide?'wide':''} ${fullscreen?'fullscreen':''}`} role="dialog" aria-modal="true" aria-label={title} tabIndex={-1} ref={ref}><div className="modal-head"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><button className="icon-button" aria-label="Tutup" onClick={onClose}><X/></button></div><div className="modal-body">{children}</div></section></div>}
export {Table} from './FilterTable.jsx';
export function Pager({total,page,onChange,size=15}){const pages=Math.max(1,Math.ceil(total/size));return <div className="pager"><span>{total?`${(page-1)*size+1}–${Math.min(page*size,total)} dari ${num(total)} data`:'0 data'}</span><div><button aria-label="Halaman sebelumnya" disabled={page<=1} onClick={()=>onChange(page-1)}><ChevronLeft size={17}/></button><span>{page} / {pages}</span><button aria-label="Halaman berikutnya" disabled={page>=pages} onClick={()=>onChange(page+1)}><ChevronRight size={17}/></button></div></div>}
export function Product({item,sku,small=false}){return <div className="product"><span className="swatch" style={{background:item?.hex||'#e3e8ee'}}></span><div><strong className={small?'':'mono'}>{sku||item?.sku}</strong><span>{item?.itemName||'SKU'} {item?.size!=null&&`/ ${sizeLabel(item.size)}`}</span></div></div>}
export function Stat({label,value,unit='pcs',icon:Icon,detail,accent=false}){return <div className={`stat ${accent?'accent':''}`}><div className="stat-top"><span>{label}</span>{Icon&&<Icon size={20}/>}</div><div className="stat-value">{num(value)} <small>{unit}</small></div><div className="stat-detail">{detail||'Data perangkat ini'}</div></div>}
export function ScanInput({onScan,placeholder='Scan barcode, lalu Enter',label='Scan barcode',value,onChange,id,nextInputId,allowPhoto=false,submitLabel,disabled=false}){
 const [v,setV]=useState(''),[camera,setCamera]=useState(false),[scanError,setScanError]=useState(''),[photoBusy,setPhotoBusy]=useState(false);
 const input=useRef(),fileInput=useRef(),queue=useRef(Promise.resolve()),sequence=useRef(0),mounted=useRef(true);const text=value??v,change=onChange||setV;
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false}},[]);
 async function submit(code){
  if(disabled||!mounted.current||!code.trim())return;const seq=++sequence.current;if(value===undefined)change('');setScanError('');
  const task=queue.current.then(async()=>{if(!mounted.current)return;try{const result=await onScan(code.trim());if(!mounted.current)return;if(result===false){if(seq===sequence.current&&value===undefined)change(code);input.current?.focus();return}if(seq===sequence.current){const next=nextInputId?document.getElementById(nextInputId):null;(next||input.current)?.focus()}}catch(e){if(!mounted.current)return;setScanError(e.message||'Scan belum tercatat');if(seq===sequence.current&&value===undefined)change(code);input.current?.focus()}});queue.current=task.catch(()=>{});await task;
 }
 async function photo(file){if(!file)return;setPhotoBusy(true);setScanError('');try{const code=await readBarcodePhoto(file);await submit(code)}catch(e){if(mounted.current)setScanError(e.message)}finally{if(mounted.current)setPhotoBusy(false)}}
 return <><div className="scan-input"><ScanLine size={23}/><input id={id} ref={input} aria-label={label} disabled={disabled||photoBusy} autoComplete="off" autoCapitalize="characters" value={text} onChange={e=>change(e.target.value)} placeholder={placeholder} onKeyDown={async e=>{if(e.key==='Enter'){e.preventDefault();await submit(text)}}}/><button type="button" disabled={disabled||photoBusy} className="icon-button" aria-label={`Scan kamera ${label}`} onClick={()=>setCamera(true)}><Camera size={21}/></button></div>
 {(allowPhoto||submitLabel)&&<div className="scan-actions">{allowPhoto&&<><input hidden ref={fileInput} type="file" accept="image/*" aria-label={`Pilih foto ${label}`} onChange={e=>{const file=e.target.files?.[0];e.target.value='';photo(file)}}/><Button type="button" variant="secondary" icon={Camera} disabled={disabled||photoBusy} onClick={()=>fileInput.current?.click()}>{photoBusy?'Membaca foto…':'Foto barcode / QR'}</Button></>}{submitLabel&&<Button type="button" disabled={disabled||photoBusy||!text.trim()} onClick={()=>submit(text)}>{submitLabel}</Button>}</div>}
 {scanError&&<p className="error-text" role="alert">{scanError}</p>}{camera&&<CameraScan onClose={()=>setCamera(false)} onResult={async code=>{setCamera(false);await submit(code)}}/>}</>;
}

function CameraScan({onClose,onResult}){const video=useRef(),[error,setError]=useState(''),[ready,setReady]=useState(false);useEffect(()=>{let stop=false,stream,reader,frame;async function start(){try{if(!navigator.mediaDevices)throw Error('Kamera tidak tersedia. Gunakan scanner handheld atau input barcode.');if('BarcodeDetector'in window){stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});if(stop){stream.getTracks().forEach(t=>t.stop());return}video.current.srcObject=stream;await video.current.play();setReady(true);const detector=new BarcodeDetector({formats:['code_128','qr_code']});const tick=async()=>{if(stop)return;try{const codes=await detector.detect(video.current);if(codes.length){stop=true;onResult(codes[0].rawValue);return}}catch{}frame=setTimeout(tick,180)};tick()}else{if(!window.ZXing)await new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/@zxing/library@0.21.3/umd/index.min.js';script.onload=resolve;script.onerror=()=>reject(Error('Pemindai kamera perlu koneksi internet saat pertama kali dimuat. Gunakan scanner handheld.'));document.head.appendChild(script)});if(stop)return;reader=new window.ZXing.BrowserMultiFormatReader();await reader.decodeFromVideoDevice(null,video.current,(result)=>{if(result&&!stop){stop=true;onResult(result.getText())}});setReady(true)}}catch(e){setError(e.message)}}start();return()=>{stop=true;clearTimeout(frame);stream?.getTracks().forEach(t=>t.stop());reader?.reset()}},[]);return <Modal title="Scan dengan kamera" onClose={onClose}><video ref={video} className="camera-video" muted playsInline/>{error?<Notice tone="red">{error}</Notice>:<p>{ready?'Arahkan barcode ke tengah kamera.':'Meminta akses kamera…'}</p>}</Modal>}

Badge.filterValue = ({status,children}) => children || labels[status] || status;
Product.filterValue = ({item,sku}) => [sku || item?.sku, item?.itemName || 'SKU', item?.size != null ? sizeLabel(item.size) : ''].filter(Boolean).join(' ');
